# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'employee_details.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 800)
        MainWindow.setMinimumSize(QtCore.QSize(0, 16))
        MainWindow.setStyleSheet("background-color:rgb(234,246,246);\n"
"border:none;\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, -1, 1201, 81))
        self.frame.setStyleSheet("background-color:rgb(247,107,138);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(370, 20, 421, 51))
        self.label.setStyleSheet("color:white;\n"
"font: 20pt \"Sans Serif\";")
        self.label.setObjectName("label")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(0, 80, 221, 721))
        self.frame_2.setStyleSheet("background-color:rgb(34,49,63);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setGeometry(QtCore.QRect(0, 0, 221, 231))
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QtWidgets.QPushButton(self.frame_3)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 16))
        self.pushButton.setStyleSheet("color:white;\n"
"font: 16pt \"Sans Serif\";\n"
"padding-bottom: 16px;\n"
"border-bottom:1px solid black;\n"
"padding-top: 16px;\n"
"background-color:rgb(34,49,63);\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_3.setStyleSheet("color:white;\n"
"font: 16pt \"Sans Serif\";\n"
"padding-bottom: 16px;\n"
"border-bottom:1px solid black;\n"
"padding-top: 16px;\n"
"background-color:rgb(34,49,63);\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_2.setStyleSheet("color:white;\n"
"font: 16pt \"Sans Serif\";\n"
"padding-bottom: 16px;\n"
"border-bottom:1px solid black;\n"
"padding-top: 16px;\n"
"background-color:rgb(34,49,63);\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_4.setStyleSheet("color:white;\n"
"font: 16pt \"Sans Serif\";\n"
"padding-bottom: 16px;\n"
"border-bottom:1px solid black;\n"
"padding-top: 16px;\n"
"background-color:rgb(34,49,63);\n"
"")
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout.addWidget(self.pushButton_4, 0, QtCore.Qt.AlignTop)
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setGeometry(QtCore.QRect(0, 600, 221, 121))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_5.setStyleSheet("color:white;\n"
"font: 16pt \"Sans Serif\";\n"
"padding-bottom: 16px;\n"
"border-bottom:1px solid black;\n"
"padding-top: 16px;\n"
"background-color:rgb(34,49,63);\n"
"")
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_2.addWidget(self.pushButton_5, 0, QtCore.Qt.AlignBottom)
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_6.setStyleSheet("color:white;\n"
"font: 16pt \"Sans Serif\";\n"
"padding-bottom: 16px;\n"
"border-bottom:1px solid black;\n"
"padding-top: 16px;\n"
"background-color:rgb(34,49,63);\n"
"")
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_2.addWidget(self.pushButton_6)
        self.frame_5 = QtWidgets.QFrame(self.centralwidget)
        self.frame_5.setGeometry(QtCore.QRect(230, 80, 961, 721))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_6 = QtWidgets.QFrame(self.frame_5)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_2 = QtWidgets.QLabel(self.frame_6)
        self.label_2.setGeometry(QtCore.QRect(10, 30, 201, 41))
        self.label_2.setStyleSheet("font: 16pt \"Sans Serif\";\n"
"")
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit.setGeometry(QtCore.QRect(20, 80, 661, 41))
        self.lineEdit.setStyleSheet("border:2px solid black;\n"
"font:20px;")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_7.clicked.connect(self.on_search_clicked)
        self.pushButton_7.setGeometry(QtCore.QRect(700, 80, 111, 41))
        self.pushButton_7.setStyleSheet("background-color:rgb(34,49,63);\n"
"font: 16pt \"Sans Serif\";\n"
"padding-left:3px;\n"
"padding-right:3px;\n"
"padding-top:1px;\n"
"border-radius:100px;\n"
"padding-bottom:1px;\n"
"color:white;")
        self.pushButton_7.setObjectName("pushButton_7")
        self.tableWidget = QtWidgets.QTableWidget(self.frame_6)
        self.tableWidget.setGeometry(QtCore.QRect(10, 180, 921, 421))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.loaddata()
        self.verticalLayout_3.addWidget(self.frame_6)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Retail Management System</span></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "Profile"))
        self.pushButton_3.setText(_translate("MainWindow", "Sales"))
        self.pushButton_2.setText(_translate("MainWindow", "Inventory"))
        self.pushButton_4.setText(_translate("MainWindow", "Employees"))
        self.pushButton_5.setText(_translate("MainWindow", "Logout"))
        self.pushButton_6.setText(_translate("MainWindow", "About"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Search Username</p></body></html>"))
        self.pushButton_7.setText(_translate("MainWindow", "Search"))
        self.tableWidget.setColumnWidth(0,190)
        self.tableWidget.setColumnWidth(1,230)
        self.tableWidget.setColumnWidth(2,150)
        self.tableWidget.setColumnWidth(3,150)
        self.tableWidget.setColumnWidth(4,150)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Name"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Email"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Role"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Age"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Gender"))
        
    def loaddata(self):
       people= [
        {"name": "prasanth", "email": "test@gmail.com", "role": "admin", "age": "16", "gender": "male"},
        {"name": "john_doe", "email": "john.doe@example.com", "role": "employee", "age": "28", "gender": "male"},
        {"name": "jane_smith", "email": "jane.smith@example.com", "role": "employee", "age": "34", "gender": "female"},
        {"name": "alice_jones", "email": "alice.jones@example.com", "role": "admin", "age": "45", "gender": "female"},
        {"name": "bob_brown", "email": "bob.brown@example.com", "role": "employee", "age": "22", "gender": "male"},
        {"name": "charlie_clark", "email": "charlie.clark@example.com", "role": "employee", "age": "29", "gender": "non-binary"},
        {"name": "dave_davis", "email": "dave.davis@example.com", "role": "employee", "age": "31", "gender": "male"},
        {"name": "eve_evans", "email": "eve.evans@example.com", "role": "admin", "age": "27", "gender": "female"},
        {"name": "frank_foster", "email": "frank.foster@example.com", "role": "employee", "age": "40", "gender": "male"},
        {"name": "grace_green", "email": "grace.green@example.com", "role": "employee", "age": "36", "gender": "female"},
        {"name": "henry_hall", "email": "henry.hall@example.com", "role": "admin", "age": "38", "gender": "male"},
        {"name": "isabel_irwin", "email": "isabel.irwin@example.com", "role": "employee", "age": "24", "gender": "female"},
        {"name": "jackie_james", "email": "jackie.james@example.com", "role": "admin", "age": "42", "gender": "female"},
        {"name": "kevin_king", "email": "kevin.king@example.com", "role": "employee", "age": "26", "gender": "male"},
        {"name": "laura_louis", "email": "laura.louis@example.com", "role": "employee", "age": "33", "gender": "female"}
        ]
       self.tableWidget.setRowCount(len(people))
       row=0
       for person in people:
            self.tableWidget.setItem(row,0,QtWidgets.QTableWidgetItem(person["name"]))
            self.tableWidget.setItem(row,1,QtWidgets.QTableWidgetItem(person["email"]))
            self.tableWidget.setItem(row,2,QtWidgets.QTableWidgetItem(person["role"]))
            self.tableWidget.setItem(row,3,QtWidgets.QTableWidgetItem(person["age"]))
            self.tableWidget.setItem(row,4,QtWidgets.QTableWidgetItem(person["gender"]))
            row+=1
        
    def on_search_clicked(self):
        print(self.lineEdit.text())
        
        


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
