# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'full.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from db.main import login


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1212, 879)
        MainWindow.setStyleSheet("\n"
"QMainWindow {\n"
"    background-color:#1e1d23;\n"
"}\n"
"QFrame{\n"
"border:none;\n"
"}\n"
"QDialog {\n"
"    background-color:#1e1d23;\n"
"}\n"
"QColorDialog {\n"
"    background-color:#1e1d23;\n"
"}\n"
"QTextEdit {\n"
"    background-color:#1e1d23;\n"
"    color: #a9b7c6;\n"
"}\n"
"QPlainTextEdit {\n"
"    selection-background-color:#007b50;\n"
"    background-color:#1e1d23;\n"
"    border-style: solid;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: transparent;\n"
"    border-bottom-color: transparent;\n"
"    border-width: 1px;\n"
"    color: #a9b7c6;\n"
"}\n"
"QPushButton{\n"
"    border-style: solid;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: transparent;\n"
"    border-bottom-color: transparent;\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    color: #a9b7c6;\n"
"    padding: 2px;\n"
"    background-color: #1e1d23;\n"
"}\n"
"QPushButton::default{\n"
"    border-style: inset;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: transparent;\n"
"    border-bottom-color: #04b97f;\n"
"    border-width: 1px;\n"
"    color: #a9b7c6;\n"
"    padding: 2px;\n"
"    background-color: #1e1d23;\n"
"}\n"
"QToolButton {\n"
"    border-style: solid;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: transparent;\n"
"    border-bottom-color: #04b97f;\n"
"    border-bottom-width: 1px;\n"
"    border-style: solid;\n"
"    color: #a9b7c6;\n"
"    padding: 2px;\n"
"    background-color: #1e1d23;\n"
"}\n"
"QToolButton:hover{\n"
"    border-style: solid;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: transparent;\n"
"    border-bottom-color: #37efba;\n"
"    border-bottom-width: 2px;\n"
"    border-style: solid;\n"
"    color: #FFFFFF;\n"
"    padding-bottom: 1px;\n"
"    background-color: #1e1d23;\n"
"}\n"
"QPushButton:hover{\n"
"    border-style: solid;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: transparent;\n"
"    border-bottom-color: #37efba;\n"
"    border-bottom-width: 1px;\n"
"    border-style: solid;\n"
"    color: #FFFFFF;\n"
"    padding-bottom: 2px;\n"
"    background-color: #1e1d23;\n"
"}\n"
"QPushButton:pressed{\n"
"    border-style: solid;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: transparent;\n"
"    border-bottom-color: #37efba;\n"
"    border-bottom-width: 2px;\n"
"    border-style: solid;\n"
"    color: #37efba;\n"
"    padding-bottom: 1px;\n"
"    background-color: #1e1d23;\n"
"}\n"
"QPushButton:disabled{\n"
"    border-style: solid;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: transparent;\n"
"    border-bottom-color: #808086;\n"
"    border-bottom-width: 2px;\n"
"    border-style: solid;\n"
"    color: #808086;\n"
"    padding-bottom: 1px;\n"
"    background-color: #1e1d23;\n"
"}\n"
"QLineEdit {\n"
"    border-width: 1px; border-radius: 4px;\n"
"    border-color: rgb(58, 58, 58);\n"
"    border-style: inset;\n"
"    padding: 0 8px;\n"
"    color: #a9b7c6;\n"
"    background:#1e1d23;\n"
"    selection-background-color:#007b50;\n"
"    selection-color: #FFFFFF;\n"
"}\n"
"QLabel {\n"
"    color: #a9b7c6;\n"
"}\n"
"QLCDNumber {\n"
"    color: #37e6b4;\n"
"}\n"
"QProgressBar {\n"
"    text-align: center;\n"
"    color: rgb(240, 240, 240);\n"
"    border-width: 1px; \n"
"    border-radius: 10px;\n"
"    border-color: rgb(58, 58, 58);\n"
"    border-style: inset;\n"
"    background-color:#1e1d23;\n"
"}\n"
"QProgressBar::chunk {\n"
"    background-color: #04b97f;\n"
"    border-radius: 5px;\n"
"}\n"
"QMenuBar {\n"
"    background-color: #1e1d23;\n"
"}\n"
"QMenuBar::item {\n"
"    color: #a9b7c6;\n"
"      spacing: 3px;\n"
"      padding: 1px 4px;\n"
"      background: #1e1d23;\n"
"}\n"
"\n"
"QMenuBar::item:selected {\n"
"      background:#1e1d23;\n"
"    color: #FFFFFF;\n"
"}\n"
"QMenu::item:selected {\n"
"    border-style: solid;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: #04b97f;\n"
"    border-bottom-color: transparent;\n"
"    border-left-width: 2px;\n"
"    color: #FFFFFF;\n"
"    padding-left:15px;\n"
"    padding-top:4px;\n"
"    padding-bottom:4px;\n"
"    padding-right:7px;\n"
"    background-color: #1e1d23;\n"
"}\n"
"QMenu::item {\n"
"    border-style: solid;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: transparent;\n"
"    border-bottom-color: transparent;\n"
"    border-bottom-width: 1px;\n"
"    border-style: solid;\n"
"    color: #a9b7c6;\n"
"    padding-left:17px;\n"
"    padding-top:4px;\n"
"    padding-bottom:4px;\n"
"    padding-right:7px;\n"
"    background-color: #1e1d23;\n"
"}\n"
"QMenu{\n"
"    background-color:#1e1d23;\n"
"}\n"
"QTabWidget {\n"
"    color:rgb(0,0,0);\n"
"    background-color:#1e1d23;\n"
"}\n"
"QTabWidget::pane {\n"
"        border-color: rgb(77,77,77);\n"
"        background-color:#1e1d23;\n"
"        border-style: solid;\n"
"        border-width: 1px;\n"
"        border-radius: 6px;\n"
"}\n"
"QTabBar::tab {\n"
"    border-style: solid;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: transparent;\n"
"    border-bottom-color: transparent;\n"
"    border-bottom-width: 1px;\n"
"    border-style: solid;\n"
"    color: #808086;\n"
"    padding: 3px;\n"
"    margin-left:3px;\n"
"    background-color: #1e1d23;\n"
"}\n"
"QTabBar::tab:selected, QTabBar::tab:last:selected, QTabBar::tab:hover {\n"
"      border-style: solid;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: transparent;\n"
"    border-bottom-color: #04b97f;\n"
"    border-bottom-width: 2px;\n"
"    border-style: solid;\n"
"    color: #FFFFFF;\n"
"    padding-left: 3px;\n"
"    padding-bottom: 2px;\n"
"    margin-left:3px;\n"
"    background-color: #1e1d23;\n"
"}\n"
"\n"
"QCheckBox {\n"
"    color: #a9b7c6;\n"
"    padding: 2px;\n"
"}\n"
"QCheckBox:disabled {\n"
"    color: #808086;\n"
"    padding: 2px;\n"
"}\n"
"\n"
"QCheckBox:hover {\n"
"    border-radius:4px;\n"
"    border-style:solid;\n"
"    padding-left: 1px;\n"
"    padding-right: 1px;\n"
"    padding-bottom: 1px;\n"
"    padding-top: 1px;\n"
"    border-width:1px;\n"
"    border-color: rgb(87, 97, 106);\n"
"    background-color:#1e1d23;\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    border-style:solid;\n"
"    border-width: 1px;\n"
"    border-color: #04b97f;\n"
"    color: #a9b7c6;\n"
"    background-color: #04b97f;\n"
"}\n"
"QCheckBox::indicator:unchecked {\n"
"\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    border-style:solid;\n"
"    border-width: 1px;\n"
"    border-color: #04b97f;\n"
"    color: #a9b7c6;\n"
"    background-color: transparent;\n"
"}\n"
"QRadioButton {\n"
"    color: #a9b7c6;\n"
"    background-color: #1e1d23;\n"
"    padding: 1px;\n"
"}\n"
"QRadioButton::indicator:checked {\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    border-style:solid;\n"
"    border-radius:5px;\n"
"    border-width: 1px;\n"
"    border-color: #04b97f;\n"
"    color: #a9b7c6;\n"
"    background-color: #04b97f;\n"
"}\n"
"QRadioButton::indicator:!checked {\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    border-style:solid;\n"
"    border-radius:5px;\n"
"    border-width: 1px;\n"
"    border-color: #04b97f;\n"
"    color: #a9b7c6;\n"
"    background-color: transparent;\n"
"}\n"
"QStatusBar {\n"
"    color:#027f7f;\n"
"}\n"
"QSpinBox {\n"
"    color: #a9b7c6;    \n"
"    background-color: #1e1d23;\n"
"}\n"
"QDoubleSpinBox {\n"
"    color: #a9b7c6;    \n"
"    background-color: #1e1d23;\n"
"}\n"
"QTimeEdit {\n"
"    color: #a9b7c6;    \n"
"    background-color: #1e1d23;\n"
"}\n"
"QDateTimeEdit {\n"
"    color: #a9b7c6;    \n"
"    background-color: #1e1d23;\n"
"}\n"
"QDateEdit {\n"
"    color: #a9b7c6;    \n"
"    background-color: #1e1d23;\n"
"}\n"
"QComboBox {\n"
"    color: #a9b7c6;    \n"
"    background: #1e1d23;\n"
"}\n"
"QComboBox:editable {\n"
"    background: #1e1d23;\n"
"    color: #a9b7c6;\n"
"    selection-background-color: #1e1d23;\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    color: #a9b7c6;    \n"
"    background: #1e1d23;\n"
"    selection-color: #FFFFFF;\n"
"    selection-background-color: #1e1d23;\n"
"}\n"
"QComboBox:!editable:on, QComboBox::drop-down:editable:on {\n"
"    color: #a9b7c6;    \n"
"    background: #1e1d23;\n"
"}\n"
"QFontComboBox {\n"
"    color: #a9b7c6;    \n"
"    background-color: #1e1d23;\n"
"}\n"
"QToolBox {\n"
"    color: #a9b7c6;\n"
"    background-color: #1e1d23;\n"
"}\n"
"QToolBox::tab {\n"
"    color: #a9b7c6;\n"
"    background-color: #1e1d23;\n"
"}\n"
"QToolBox::tab:selected {\n"
"    color: #FFFFFF;\n"
"    background-color: #1e1d23;\n"
"}\n"
"QScrollArea {\n"
"    color: #FFFFFF;\n"
"    background-color: #1e1d23;\n"
"}\n"
"QSlider::groove:horizontal {\n"
"    height: 5px;\n"
"    background: #04b97f;\n"
"}\n"
"QSlider::groove:vertical {\n"
"    width: 5px;\n"
"    background: #04b97f;\n"
"}\n"
"QSlider::handle:horizontal {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #b4b4b4, stop:1 #8f8f8f);\n"
"    border: 1px solid #5c5c5c;\n"
"    width: 14px;\n"
"    margin: -5px 0;\n"
"    border-radius: 7px;\n"
"}\n"
"QSlider::handle:vertical {\n"
"    background: qlineargradient(x1:1, y1:1, x2:0, y2:0, stop:0 #b4b4b4, stop:1 #8f8f8f);\n"
"    border: 1px solid #5c5c5c;\n"
"    height: 14px;\n"
"    margin: 0 -5px;\n"
"    border-radius: 7px;\n"
"}\n"
"QSlider::add-page:horizontal {\n"
"    background: white;\n"
"}\n"
"QSlider::add-page:vertical {\n"
"    background: white;\n"
"}\n"
"QSlider::sub-page:horizontal {\n"
"    background: #04b97f;\n"
"}\n"
"QSlider::sub-page:vertical {\n"
"    background: #04b97f;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.rms_main = QtWidgets.QWidget()
        self.rms_main.setObjectName("rms_main")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.rms_main)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame = QtWidgets.QFrame(self.rms_main)
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setStyleSheet("background-color:rgb(19, 19, 19);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_3.addWidget(self.frame_4)
        self.horizontalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_3.setContentsMargins(30, 0, 30, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.label_3 = QtWidgets.QLabel(self.frame_5)
        self.label_3.setMaximumSize(QtCore.QSize(500, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3, 0, QtCore.Qt.AlignHCenter)
        self.label_4 = QtWidgets.QLabel(self.frame_5)
        self.label_4.setMaximumSize(QtCore.QSize(150, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4, 0, QtCore.Qt.AlignHCenter)
        self.label_5 = QtWidgets.QLabel(self.frame_5)
        self.label_5.setMaximumSize(QtCore.QSize(500, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5, 0, QtCore.Qt.AlignHCenter)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_2.setMaximumSize(QtCore.QSize(200, 200))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"height:40px;\n"
"margin-top:60;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_3.addWidget(self.pushButton_2, 0, QtCore.Qt.AlignHCenter)
        self.pushButton = QtWidgets.QPushButton(self.frame_5)
        self.pushButton.setMaximumSize(QtCore.QSize(200, 200))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
"height:40px;\n"
"margin-top:20px;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(lambda: self.stackedWidget.setCurrentWidget(self.rms_login))
        self.pushButton_2.clicked.connect(lambda: self.stackedWidget.setCurrentWidget(self.rms_signup))
        self.verticalLayout_3.addWidget(self.pushButton, 0, QtCore.Qt.AlignHCenter)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.horizontalLayout_4.addWidget(self.frame_5)
        self.horizontalLayout.addWidget(self.frame_3)
        self.verticalLayout_4.addWidget(self.frame)
        self.stackedWidget.addWidget(self.rms_main)
        self.rms_signup = QtWidgets.QWidget()
        self.rms_signup.setObjectName("rms_signup")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.rms_signup)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_6 = QtWidgets.QFrame(self.rms_signup)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_7 = QtWidgets.QFrame(self.frame_6)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.frame_7)
        self.label_6.setMinimumSize(QtCore.QSize(0, 0))
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 200))
        self.label_6.setStyleSheet("font: 16pt \"Sans Serif\";")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_6.addWidget(self.label_6)
        self.frame_8 = QtWidgets.QFrame(self.frame_7)
        self.frame_8.setMinimumSize(QtCore.QSize(400, 500))
        self.frame_8.setMaximumSize(QtCore.QSize(3000, 16777215))
        self.frame_8.setStyleSheet("QFrame{\n"
"margin-top:90;\n"
"font:16pt\n"
"}\n"
"QPushButton{\n"
"width:100px;\n"
"}\n"
"")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_8)
        self.lineEdit.setMinimumSize(QtCore.QSize(50, 60))
        self.lineEdit.setStyleSheet("width:300px;\n"
"font: 16pt \"Sans Serif\";")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_7.addWidget(self.lineEdit)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_8)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(0, 60))
        self.lineEdit_2.setStyleSheet("font: 16pt \"Sans Serif\";")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_7.addWidget(self.lineEdit_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_3.setMinimumSize(QtCore.QSize(100, 60))
        self.pushButton_3.setStyleSheet("font: 16pt \"Sans Serif\";")
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_7.addWidget(self.pushButton_3)
        self.verticalLayout_6.addWidget(self.frame_8, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout_5.addWidget(self.frame_7, 0, QtCore.Qt.AlignVCenter)
        self.horizontalLayout_2.addWidget(self.frame_6)
        self.stackedWidget.addWidget(self.rms_signup)
        self.rms_login = QtWidgets.QWidget()
        self.rms_login.setObjectName("rms_login")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.rms_login)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_9 = QtWidgets.QFrame(self.rms_login)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_10 = QtWidgets.QFrame(self.frame_9)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_7 = QtWidgets.QLabel(self.frame_10)
        self.label_7.setMinimumSize(QtCore.QSize(0, 0))
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 200))
        self.label_7.setObjectName("label_7")
        self.verticalLayout_9.addWidget(self.label_7)
        self.frame_11 = QtWidgets.QFrame(self.frame_10)
        self.frame_11.setMinimumSize(QtCore.QSize(400, 500))
        self.frame_11.setMaximumSize(QtCore.QSize(3000, 16777215))
        self.frame_11.setStyleSheet("QFrame{\n"
"margin-top:90;\n"
"font:16pt\n"
"}\n"
"QPushButton{\n"
"width:100px;\n"
"}\n"
"")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame_11)
        self.lineEdit_3.setMinimumSize(QtCore.QSize(50, 60))
        self.lineEdit_3.setStyleSheet("width:300px;\n"
"font: 16pt \"Sans Serif\";")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout_10.addWidget(self.lineEdit_3)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame_11)
        self.lineEdit_4.setMinimumSize(QtCore.QSize(0, 60))
        self.lineEdit_4.setStyleSheet("font: 16pt \"Sans Serif\";")
        self.lineEdit_4.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout_10.addWidget(self.lineEdit_4)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_11)
        self.pushButton_4.setMinimumSize(QtCore.QSize(100, 60))
        self.pushButton_4.setStyleSheet("font: 16pt \"Sans Serif\";")
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_10.addWidget(self.pushButton_4)
        self.verticalLayout_9.addWidget(self.frame_11, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.horizontalLayout_6.addWidget(self.frame_10)
        self.horizontalLayout_5.addWidget(self.frame_9)
        self.stackedWidget.addWidget(self.rms_login)
        self.rms_dashboard = QtWidgets.QWidget()
        self.rms_dashboard.setObjectName("rms_dashboard")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.rms_dashboard)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.frame_12 = QtWidgets.QFrame(self.rms_dashboard)
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_12)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_13 = QtWidgets.QFrame(self.frame_12)
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_13)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame_14 = QtWidgets.QFrame(self.frame_13)
        self.frame_14.setMinimumSize(QtCore.QSize(1000, 60))
        self.frame_14.setStyleSheet("QFrame{\n"
"text-align:center;\n"
"}\n"
"")
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_14)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_8 = QtWidgets.QLabel(self.frame_14)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_12.addWidget(self.label_8)
        self.verticalLayout_11.addWidget(self.frame_14)
        self.verticalLayout_8.addWidget(self.frame_13, 0, QtCore.Qt.AlignTop)
        self.frame_15 = QtWidgets.QFrame(self.frame_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_15.sizePolicy().hasHeightForWidth())
        self.frame_15.setSizePolicy(sizePolicy)
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_15)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.frame_16 = QtWidgets.QFrame(self.frame_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_16.sizePolicy().hasHeightForWidth())
        self.frame_16.setSizePolicy(sizePolicy)
        self.frame_16.setMinimumSize(QtCore.QSize(250, 0))
        self.frame_16.setSizeIncrement(QtCore.QSize(0, 0))
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_16)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.frame_17 = QtWidgets.QFrame(self.frame_16)
        self.frame_17.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_17.setStyleSheet("QPushButton{\n"
"padding:20px 10px;\n"
"}\n"
"QPushButton{\n"
"font:16pt;\n"
"}")
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_17)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.profile_btn = QtWidgets.QPushButton(self.frame_17)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../mnt/c/Users/prasa/Downloads/user (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.profile_btn.setIcon(icon)
        self.profile_btn.setIconSize(QtCore.QSize(20, 20))
        self.profile_btn.setObjectName("profile_btn")
        self.verticalLayout_14.addWidget(self.profile_btn)
        self.sales_btn = QtWidgets.QPushButton(self.frame_17)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../../../../mnt/c/Users/prasa/Downloads/sales.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sales_btn.setIcon(icon1)
        self.sales_btn.setIconSize(QtCore.QSize(20, 20))
        self.sales_btn.setObjectName("sales_btn")
        self.verticalLayout_14.addWidget(self.sales_btn)
        self.emp_btn = QtWidgets.QPushButton(self.frame_17)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../../../../mnt/c/Users/prasa/Downloads/employee.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.emp_btn.setIcon(icon2)
        self.emp_btn.setIconSize(QtCore.QSize(20, 20))
        self.emp_btn.setObjectName("emp_btn")
        self.verticalLayout_14.addWidget(self.emp_btn)
        self.inventory_btn = QtWidgets.QPushButton(self.frame_17)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../../../../../mnt/c/Users/prasa/Downloads/inspection.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.inventory_btn.setIcon(icon3)
        self.inventory_btn.setIconSize(QtCore.QSize(20, 20))
        self.inventory_btn.setObjectName("inventory_btn")
        self.verticalLayout_14.addWidget(self.inventory_btn, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_13.addWidget(self.frame_17)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem4)
        self.frame_18 = QtWidgets.QFrame(self.frame_16)
        self.frame_18.setStyleSheet("QPushButton{\n"
"padding:20px 10px;\n"
"}\n"
"QPushButton{\n"
"font:16pt;\n"
"}")
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_18)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.logout_btn = QtWidgets.QPushButton(self.frame_18)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../../../../../mnt/c/Users/prasa/Downloads/logout.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.logout_btn.setIcon(icon4)
        self.logout_btn.setIconSize(QtCore.QSize(20, 20))
        self.logout_btn.setObjectName("logout_btn")
        self.verticalLayout_15.addWidget(self.logout_btn, 0, QtCore.Qt.AlignBottom)
        self.abt_btn = QtWidgets.QPushButton(self.frame_18)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../../../../../mnt/c/Users/prasa/Downloads/information.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.abt_btn.setIcon(icon5)
        self.abt_btn.setIconSize(QtCore.QSize(20, 20))
        self.abt_btn.setObjectName("abt_btn")
        self.verticalLayout_15.addWidget(self.abt_btn)
        self.verticalLayout_13.addWidget(self.frame_18)
        self.horizontalLayout_7.addWidget(self.frame_16)
        self.frame_19 = QtWidgets.QFrame(self.frame_15)
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frame_19)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setSpacing(0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.frame_19)
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.ProfilePage = QtWidgets.QWidget()
        self.ProfilePage.setObjectName("ProfilePage")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.ProfilePage)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem5)
        self.frame_20 = QtWidgets.QFrame(self.ProfilePage)
        self.frame_20.setMinimumSize(QtCore.QSize(400, 0))
        self.frame_20.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_20.setStyleSheet("QLabel{\n"
"font:16pt;\n"
"}")
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.frame_20)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setSpacing(0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.frame_21 = QtWidgets.QFrame(self.frame_20)
        self.frame_21.setMinimumSize(QtCore.QSize(0, 600))
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_21)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.frame_22 = QtWidgets.QFrame(self.frame_21)
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.frame_22)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_9 = QtWidgets.QLabel(self.frame_22)
        self.label_9.setMinimumSize(QtCore.QSize(0, 75))
        self.label_9.setObjectName("label_9")
        self.verticalLayout_18.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(self.frame_22)
        self.label_10.setMinimumSize(QtCore.QSize(0, 75))
        self.label_10.setObjectName("label_10")
        self.verticalLayout_18.addWidget(self.label_10)
        self.label_11 = QtWidgets.QLabel(self.frame_22)
        self.label_11.setMinimumSize(QtCore.QSize(0, 75))
        self.label_11.setObjectName("label_11")
        self.verticalLayout_18.addWidget(self.label_11)
        self.label_12 = QtWidgets.QLabel(self.frame_22)
        self.label_12.setMinimumSize(QtCore.QSize(0, 75))
        self.label_12.setObjectName("label_12")
        self.verticalLayout_18.addWidget(self.label_12)
        self.label_13 = QtWidgets.QLabel(self.frame_22)
        self.label_13.setMinimumSize(QtCore.QSize(0, 75))
        self.label_13.setStyleSheet("")
        self.label_13.setObjectName("label_13")
        self.verticalLayout_18.addWidget(self.label_13)
        self.horizontalLayout_9.addWidget(self.frame_22)
        self.frame_23 = QtWidgets.QFrame(self.frame_21)
        self.frame_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.frame_23)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.label_14 = QtWidgets.QLabel(self.frame_23)
        self.label_14.setMinimumSize(QtCore.QSize(0, 75))
        self.label_14.setObjectName("label_14")
        self.verticalLayout_19.addWidget(self.label_14)
        self.label_15 = QtWidgets.QLabel(self.frame_23)
        self.label_15.setMinimumSize(QtCore.QSize(0, 75))
        self.label_15.setObjectName("label_15")
        self.verticalLayout_19.addWidget(self.label_15)
        self.label_16 = QtWidgets.QLabel(self.frame_23)
        self.label_16.setMinimumSize(QtCore.QSize(0, 75))
        self.label_16.setObjectName("label_16")
        self.verticalLayout_19.addWidget(self.label_16)
        self.label_17 = QtWidgets.QLabel(self.frame_23)
        self.label_17.setMinimumSize(QtCore.QSize(0, 75))
        self.label_17.setObjectName("label_17")
        self.verticalLayout_19.addWidget(self.label_17)
        self.label_18 = QtWidgets.QLabel(self.frame_23)
        self.label_18.setMinimumSize(QtCore.QSize(0, 75))
        self.label_18.setStyleSheet("")
        self.label_18.setObjectName("label_18")
        self.verticalLayout_19.addWidget(self.label_18)
        self.horizontalLayout_9.addWidget(self.frame_23)
        self.verticalLayout_17.addWidget(self.frame_21, 0, QtCore.Qt.AlignVCenter)
        self.horizontalLayout_8.addWidget(self.frame_20)
        self.frame_24 = QtWidgets.QFrame(self.ProfilePage)
        self.frame_24.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_24.setObjectName("frame_24")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.frame_24)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.label_19 = QtWidgets.QLabel(self.frame_24)
        self.label_19.setStyleSheet("QLabel{\n"
"border-radius:100;\n"
"}")
        self.label_19.setText("")
        self.label_19.setPixmap(QtGui.QPixmap("../../../../../mnt/c/Users/prasa/Downloads/user_profile (1).jpg"))
        self.label_19.setObjectName("label_19")
        self.verticalLayout_20.addWidget(self.label_19)
        self.horizontalLayout_8.addWidget(self.frame_24, 0, QtCore.Qt.AlignHCenter)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem6)
        self.stackedWidget_2.addWidget(self.ProfilePage)
        self.Employee = QtWidgets.QWidget()
        self.Employee.setObjectName("Employee")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.Employee)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.frame_25 = QtWidgets.QFrame(self.Employee)
        self.frame_25.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_25.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_25.setObjectName("frame_25")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.frame_25)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.frame_26 = QtWidgets.QFrame(self.frame_25)
        self.frame_26.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_26.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_26.setObjectName("frame_26")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.frame_26)
        self.verticalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_23.setSpacing(0)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.frame_27 = QtWidgets.QFrame(self.frame_26)
        self.frame_27.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_27.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_27.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_27.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_27.setObjectName("frame_27")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_27)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.frame_28 = QtWidgets.QFrame(self.frame_27)
        self.frame_28.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_28.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_28.setObjectName("frame_28")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_28)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.frame_28)
        self.lineEdit_5.setMinimumSize(QtCore.QSize(600, 50))
        self.lineEdit_5.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_5.setStyleSheet("font:16pt")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.horizontalLayout_11.addWidget(self.lineEdit_5)
        spacerItem7 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem7)
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_28)
        self.pushButton_7.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_7.setStyleSheet("font:16pt;\n"
"margin-right:10;")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../../../../../mnt/c/Users/prasa/Downloads/magnifying-glass.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_7.setIcon(icon6)
        self.pushButton_7.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_11.addWidget(self.pushButton_7)
        self.horizontalLayout_10.addWidget(self.frame_28)
        self.verticalLayout_23.addWidget(self.frame_27)
        self.frame_29 = QtWidgets.QFrame(self.frame_26)
        self.frame_29.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_29.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_29.setObjectName("frame_29")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.frame_29)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.frame_30 = QtWidgets.QFrame(self.frame_29)
        self.frame_30.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_30.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_30.setObjectName("frame_30")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.frame_30)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.tableWidget = QtWidgets.QTableWidget(self.frame_30)
        self.tableWidget.setStyleSheet("font:12pt;")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.verticalLayout_25.addWidget(self.tableWidget)
        self.verticalLayout_24.addWidget(self.frame_30)
        self.frame_31 = QtWidgets.QFrame(self.frame_29)
        self.frame_31.setMaximumSize(QtCore.QSize(500, 100))
        self.frame_31.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_31.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_31.setObjectName("frame_31")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.frame_31)
        self.verticalLayout_26.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_26.setSpacing(0)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.frame_32 = QtWidgets.QFrame(self.frame_31)
        self.frame_32.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_32.setMaximumSize(QtCore.QSize(500, 100))
        self.frame_32.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_32.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_32.setObjectName("frame_32")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_32)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(9)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_32)
        self.pushButton_9.setStyleSheet("font:16pt;\n"
"padding : 10px 20px;")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("../../../../../mnt/c/Users/prasa/Downloads/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_9.setIcon(icon7)
        self.pushButton_9.setIconSize(QtCore.QSize(20, 16))
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_12.addWidget(self.pushButton_9)
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_32)
        self.pushButton_8.setStyleSheet("font:16pt;\n"
"padding:10px 20px")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("../../../../../mnt/c/Users/prasa/Downloads/update.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_8.setIcon(icon8)
        self.pushButton_8.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_12.addWidget(self.pushButton_8)
        self.verticalLayout_26.addWidget(self.frame_32)
        self.verticalLayout_24.addWidget(self.frame_31, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_23.addWidget(self.frame_29)
        self.verticalLayout_22.addWidget(self.frame_26)
        self.verticalLayout_21.addWidget(self.frame_25)
        self.stackedWidget_2.addWidget(self.Employee)
        self.Inventory = QtWidgets.QWidget()
        self.Inventory.setObjectName("Inventory")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout(self.Inventory)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.frame_33 = QtWidgets.QFrame(self.Inventory)
        self.frame_33.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_33.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_33.setObjectName("frame_33")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout(self.frame_33)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.frame_34 = QtWidgets.QFrame(self.frame_33)
        self.frame_34.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_34.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_34.setObjectName("frame_34")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout(self.frame_34)
        self.verticalLayout_29.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_29.setSpacing(0)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.frame_35 = QtWidgets.QFrame(self.frame_34)
        self.frame_35.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_35.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_35.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_35.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_35.setObjectName("frame_35")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_35)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.frame_36 = QtWidgets.QFrame(self.frame_35)
        self.frame_36.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_36.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_36.setObjectName("frame_36")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_36)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.frame_36)
        self.lineEdit_6.setMinimumSize(QtCore.QSize(600, 50))
        self.lineEdit_6.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_6.setStyleSheet("font:16pt")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.horizontalLayout_14.addWidget(self.lineEdit_6)
        spacerItem8 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem8)
        self.pushButton_10 = QtWidgets.QPushButton(self.frame_36)
        self.pushButton_10.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_10.setStyleSheet("font:16pt;\n"
"margin-right:10;")
        self.pushButton_10.setIcon(icon6)
        self.pushButton_10.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_14.addWidget(self.pushButton_10)
        self.horizontalLayout_13.addWidget(self.frame_36)
        self.verticalLayout_29.addWidget(self.frame_35)
        self.frame_37 = QtWidgets.QFrame(self.frame_34)
        self.frame_37.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_37.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_37.setObjectName("frame_37")
        self.verticalLayout_30 = QtWidgets.QVBoxLayout(self.frame_37)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.frame_38 = QtWidgets.QFrame(self.frame_37)
        self.frame_38.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_38.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_38.setObjectName("frame_38")
        self.verticalLayout_31 = QtWidgets.QVBoxLayout(self.frame_38)
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.frame_38)
        self.tableWidget_2.setStyleSheet("font:12pt;")
        self.tableWidget_2.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(6)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        self.verticalLayout_31.addWidget(self.tableWidget_2)
        self.verticalLayout_30.addWidget(self.frame_38)
        self.frame_39 = QtWidgets.QFrame(self.frame_37)
        self.frame_39.setMaximumSize(QtCore.QSize(500, 100))
        self.frame_39.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_39.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_39.setObjectName("frame_39")
        self.verticalLayout_32 = QtWidgets.QVBoxLayout(self.frame_39)
        self.verticalLayout_32.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_32.setSpacing(0)
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.frame_40 = QtWidgets.QFrame(self.frame_39)
        self.frame_40.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_40.setMaximumSize(QtCore.QSize(500, 100))
        self.frame_40.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_40.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_40.setObjectName("frame_40")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_40)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setSpacing(9)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.pushButton_12 = QtWidgets.QPushButton(self.frame_40)
        self.pushButton_12.setStyleSheet("font:16pt;\n"
"padding:10px 20px")
        self.pushButton_12.setIcon(icon8)
        self.pushButton_12.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout_15.addWidget(self.pushButton_12)
        self.verticalLayout_32.addWidget(self.frame_40)
        self.verticalLayout_30.addWidget(self.frame_39, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_29.addWidget(self.frame_37)
        self.verticalLayout_28.addWidget(self.frame_34)
        self.verticalLayout_27.addWidget(self.frame_33)
        self.stackedWidget_2.addWidget(self.Inventory)
        self.verticalLayout_16.addWidget(self.stackedWidget_2)
        self.horizontalLayout_7.addWidget(self.frame_19)
        self.verticalLayout_8.addWidget(self.frame_15)
        self.horizontalLayout_16.addWidget(self.frame_12)
        self.stackedWidget.addWidget(self.rms_dashboard)
        self.verticalLayout.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.stackedWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Retail Management</span></p></body></html>"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">System</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Create new account</p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">or</p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Login to your existing account</p></body></html>"))
        self.pushButton_2.setText(_translate("MainWindow", "Sign Up"))
        self.pushButton.setText(_translate("MainWindow", "Login"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:26pt; font-weight:600;\">Create a new account</span></p></body></html>"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Username"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Password"))
        self.pushButton_3.setText(_translate("MainWindow", "SignUp"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:26pt; font-weight:600;\">Login to your existing account</span></p></body></html>"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "Username"))
        self.lineEdit_4.setPlaceholderText(_translate("MainWindow", "Password"))
        self.pushButton_4.setText(_translate("MainWindow", "Login"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; font-weight:600;\">Retail Management System</span></p></body></html>"))
        self.profile_btn.setText(_translate("MainWindow", "Profile"))
        self.sales_btn.setText(_translate("MainWindow", "Sales"))
        self.emp_btn.setText(_translate("MainWindow", "Employees"))
        self.inventory_btn.setText(_translate("MainWindow", "Inventory"))
        self.logout_btn.setText(_translate("MainWindow", "Logout"))
        self.abt_btn.setText(_translate("MainWindow", "About"))
        self.label_9.setText(_translate("MainWindow", " Username :"))
        self.label_10.setText(_translate("MainWindow", "Age :"))
        self.label_11.setText(_translate("MainWindow", "Gender :"))
        self.label_12.setText(_translate("MainWindow", "Email :"))
        self.label_13.setText(_translate("MainWindow", "Role :"))
        self.label_14.setText(_translate("MainWindow", " Username :"))
        self.label_15.setText(_translate("MainWindow", "Age :"))
        self.label_16.setText(_translate("MainWindow", "Gender :"))
        self.label_17.setText(_translate("MainWindow", "Email :"))
        self.label_18.setText(_translate("MainWindow", "Role :"))
        self.lineEdit_5.setPlaceholderText(_translate("MainWindow", "Search for an employee"))
        self.pushButton_7.setText(_translate("MainWindow", "Search"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Name"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Username"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Email"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Age"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Gender"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Role"))
        self.pushButton_9.setText(_translate("MainWindow", "Delete"))
        self.pushButton_8.setText(_translate("MainWindow", "Update"))
        self.lineEdit_6.setPlaceholderText(_translate("MainWindow", "Search for a product"))
        self.pushButton_10.setText(_translate("MainWindow", "Search"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ProductId"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Category"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Description"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Stock"))
        item = self.tableWidget_2.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Price"))
        self.pushButton_12.setText(_translate("MainWindow", "Update"))
        self.emp_btn.clicked.connect(lambda: self.stackedWidget.setCurrentWidget(self.Employee))
        self.profile_btn.clicked.connect(lambda: self.stackedWidget.setCurrentWidget(self.ProfilePage))
        self.inventory_btn.clicked.connect(lambda: self.stackedWidget.setCurrentWidget(self.Inventory))
        


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
