# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'full3.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from db.main import login,get_all_employee_details,get_employee_details,get_all_product_details,update_product_handler,update_emp_handler


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1900, 1050)
        MainWindow.setStyleSheet("QFrame{\n"
"border:none\n"
"}\n"
"QMainWindow {\n"
"    background-color:#1e1d23;\n"
"}\n"
"QDialog {\n"
"    background-color:#1e1d23;\n"
"}\n"
"QColorDialog {\n"
"    background-color:#1e1d23;\n"
"}\n"
"QTextEdit {\n"
"    background-color:#1e1d23;\n"
"    color: #a9b7c6;\n"
"}\n"
"QPlainTextEdit {\n"
"    selection-background-color:#007b50;\n"
"    background-color:#1e1d23;\n"
"    border-style: solid;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: transparent;\n"
"    border-bottom-color: transparent;\n"
"    border-width: 1px;\n"
"    color: #a9b7c6;\n"
"}\n"
"QPushButton{\n"
"    border-style: solid;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: transparent;\n"
"    border-bottom-color: transparent;\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    color: #a9b7c6;\n"
"    padding: 2px;\n"
"    background-color: #1e1d23;\n"
"}\n"
"QPushButton::default{\n"
"    border-style: inset;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: transparent;\n"
"    border-bottom-color: #04b97f;\n"
"    border-width: 1px;\n"
"    color: #a9b7c6;\n"
"    padding: 2px;\n"
"    background-color: #1e1d23;\n"
"}\n"
"QToolButton {\n"
"    border-style: solid;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: transparent;\n"
"    border-bottom-color: #04b97f;\n"
"    border-bottom-width: 1px;\n"
"    border-style: solid;\n"
"    color: #a9b7c6;\n"
"    padding: 2px;\n"
"    background-color: #1e1d23;\n"
"}\n"
"QToolButton:hover{\n"
"    border-style: solid;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: transparent;\n"
"    border-bottom-color: #37efba;\n"
"    border-bottom-width: 2px;\n"
"    border-style: solid;\n"
"    color: #FFFFFF;\n"
"    padding-bottom: 1px;\n"
"    background-color: #1e1d23;\n"
"}\n"
"QPushButton:hover{\n"
"    border-style: solid;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: transparent;\n"
"    border-bottom-color: #37efba;\n"
"    border-bottom-width: 1px;\n"
"    border-style: solid;\n"
"    color: #FFFFFF;\n"
"    padding-bottom: 2px;\n"
"    background-color: #1e1d23;\n"
"}\n"
"QPushButton:pressed{\n"
"    border-style: solid;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: transparent;\n"
"    border-bottom-color: #37efba;\n"
"    border-bottom-width: 2px;\n"
"    border-style: solid;\n"
"    color: #37efba;\n"
"    padding-bottom: 1px;\n"
"    background-color: #1e1d23;\n"
"}\n"
"QPushButton:disabled{\n"
"    border-style: solid;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: transparent;\n"
"    border-bottom-color: #808086;\n"
"    border-bottom-width: 2px;\n"
"    border-style: solid;\n"
"    color: #808086;\n"
"    padding-bottom: 1px;\n"
"    background-color: #1e1d23;\n"
"}\n"
"QLineEdit {\n"
"    border-width: 1px; border-radius: 4px;\n"
"    border-color: rgb(58, 58, 58);\n"
"    border-style: inset;\n"
"    padding: 0 8px;\n"
"    color: #a9b7c6;\n"
"    background:#1e1d23;\n"
"    selection-background-color:#007b50;\n"
"    selection-color: #FFFFFF;\n"
"}\n"
"QLabel {\n"
"    color: #a9b7c6;\n"
"}\n"
"QLCDNumber {\n"
"    color: #37e6b4;\n"
"}\n"
"QProgressBar {\n"
"    text-align: center;\n"
"    color: rgb(240, 240, 240);\n"
"    border-width: 1px; \n"
"    border-radius: 10px;\n"
"    border-color: rgb(58, 58, 58);\n"
"    border-style: inset;\n"
"    background-color:#1e1d23;\n"
"}\n"
"QProgressBar::chunk {\n"
"    background-color: #04b97f;\n"
"    border-radius: 5px;\n"
"}\n"
"QMenuBar {\n"
"    background-color: #1e1d23;\n"
"}\n"
"QMenuBar::item {\n"
"    color: #a9b7c6;\n"
"      spacing: 3px;\n"
"      padding: 1px 4px;\n"
"      background: #1e1d23;\n"
"}\n"
"\n"
"QMenuBar::item:selected {\n"
"      background:#1e1d23;\n"
"    color: #FFFFFF;\n"
"}\n"
"QMenu::item:selected {\n"
"    border-style: solid;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: #04b97f;\n"
"    border-bottom-color: transparent;\n"
"    border-left-width: 2px;\n"
"    color: #FFFFFF;\n"
"    padding-left:15px;\n"
"    padding-top:4px;\n"
"    padding-bottom:4px;\n"
"    padding-right:7px;\n"
"    background-color: #1e1d23;\n"
"}\n"
"QMenu::item {\n"
"    border-style: solid;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: transparent;\n"
"    border-bottom-color: transparent;\n"
"    border-bottom-width: 1px;\n"
"    border-style: solid;\n"
"    color: #a9b7c6;\n"
"    padding-left:17px;\n"
"    padding-top:4px;\n"
"    padding-bottom:4px;\n"
"    padding-right:7px;\n"
"    background-color: #1e1d23;\n"
"}\n"
"QMenu{\n"
"    background-color:#1e1d23;\n"
"}\n"
"QTabWidget {\n"
"    color:rgb(0,0,0);\n"
"    background-color:#1e1d23;\n"
"}\n"
"QTabWidget::pane {\n"
"        border-color: rgb(77,77,77);\n"
"        background-color:#1e1d23;\n"
"        border-style: solid;\n"
"        border-width: 1px;\n"
"        border-radius: 6px;\n"
"}\n"
"QTabBar::tab {\n"
"    border-style: solid;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: transparent;\n"
"    border-bottom-color: transparent;\n"
"    border-bottom-width: 1px;\n"
"    border-style: solid;\n"
"    color: #808086;\n"
"    padding: 3px;\n"
"    margin-left:3px;\n"
"    background-color: #1e1d23;\n"
"}\n"
"QTabBar::tab:selected, QTabBar::tab:last:selected, QTabBar::tab:hover {\n"
"      border-style: solid;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: transparent;\n"
"    border-bottom-color: #04b97f;\n"
"    border-bottom-width: 2px;\n"
"    border-style: solid;\n"
"    color: #FFFFFF;\n"
"    padding-left: 3px;\n"
"    padding-bottom: 2px;\n"
"    margin-left:3px;\n"
"    background-color: #1e1d23;\n"
"}\n"
"\n"
"QCheckBox {\n"
"    color: #a9b7c6;\n"
"    padding: 2px;\n"
"}\n"
"QCheckBox:disabled {\n"
"    color: #808086;\n"
"    padding: 2px;\n"
"}\n"
"\n"
"QCheckBox:hover {\n"
"    border-radius:4px;\n"
"    border-style:solid;\n"
"    padding-left: 1px;\n"
"    padding-right: 1px;\n"
"    padding-bottom: 1px;\n"
"    padding-top: 1px;\n"
"    border-width:1px;\n"
"    border-color: rgb(87, 97, 106);\n"
"    background-color:#1e1d23;\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    border-style:solid;\n"
"    border-width: 1px;\n"
"    border-color: #04b97f;\n"
"    color: #a9b7c6;\n"
"    background-color: #04b97f;\n"
"}\n"
"QCheckBox::indicator:unchecked {\n"
"\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    border-style:solid;\n"
"    border-width: 1px;\n"
"    border-color: #04b97f;\n"
"    color: #a9b7c6;\n"
"    background-color: transparent;\n"
"}\n"
"QRadioButton {\n"
"    color: #a9b7c6;\n"
"    background-color: #1e1d23;\n"
"    padding: 1px;\n"
"}\n"
"QRadioButton::indicator:checked {\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    border-style:solid;\n"
"    border-radius:5px;\n"
"    border-width: 1px;\n"
"    border-color: #04b97f;\n"
"    color: #a9b7c6;\n"
"    background-color: #04b97f;\n"
"}\n"
"QRadioButton::indicator:!checked {\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    border-style:solid;\n"
"    border-radius:5px;\n"
"    border-width: 1px;\n"
"    border-color: #04b97f;\n"
"    color: #a9b7c6;\n"
"    background-color: transparent;\n"
"}\n"
"QStatusBar {\n"
"    color:#027f7f;\n"
"}\n"
"QSpinBox {\n"
"    color: #a9b7c6;    \n"
"    background-color: #1e1d23;\n"
"}\n"
"QDoubleSpinBox {\n"
"    color: #a9b7c6;    \n"
"    background-color: #1e1d23;\n"
"}\n"
"QTimeEdit {\n"
"    color: #a9b7c6;    \n"
"    background-color: #1e1d23;\n"
"}\n"
"QDateTimeEdit {\n"
"    color: #a9b7c6;    \n"
"    background-color: #1e1d23;\n"
"}\n"
"QDateEdit {\n"
"    color: #a9b7c6;    \n"
"    background-color: #1e1d23;\n"
"}\n"
"QComboBox {\n"
"    color: #a9b7c6;    \n"
"    background: #1e1d23;\n"
"}\n"
"QComboBox:editable {\n"
"    background: #1e1d23;\n"
"    color: #a9b7c6;\n"
"    selection-background-color: #1e1d23;\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    color: #a9b7c6;    \n"
"    background: #1e1d23;\n"
"    selection-color: #FFFFFF;\n"
"    selection-background-color: #1e1d23;\n"
"}\n"
"QComboBox:!editable:on, QComboBox::drop-down:editable:on {\n"
"    color: #a9b7c6;    \n"
"    background: #1e1d23;\n"
"}\n"
"QFontComboBox {\n"
"    color: #a9b7c6;    \n"
"    background-color: #1e1d23;\n"
"}\n"
"QToolBox {\n"
"    color: #a9b7c6;\n"
"    background-color: #1e1d23;\n"
"}\n"
"QToolBox::tab {\n"
"    color: #a9b7c6;\n"
"    background-color: #1e1d23;\n"
"}\n"
"QToolBox::tab:selected {\n"
"    color: #FFFFFF;\n"
"    background-color: #1e1d23;\n"
"}\n"
"QScrollArea {\n"
"    color: #FFFFFF;\n"
"    background-color: #1e1d23;\n"
"}\n"
"QSlider::groove:horizontal {\n"
"    height: 5px;\n"
"    background: #04b97f;\n"
"}\n"
"QSlider::groove:vertical {\n"
"    width: 5px;\n"
"    background: #04b97f;\n"
"}\n"
"QSlider::handle:horizontal {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #b4b4b4, stop:1 #8f8f8f);\n"
"    border: 1px solid #5c5c5c;\n"
"    width: 14px;\n"
"    margin: -5px 0;\n"
"    border-radius: 7px;\n"
"}\n"
"QSlider::handle:vertical {\n"
"    background: qlineargradient(x1:1, y1:1, x2:0, y2:0, stop:0 #b4b4b4, stop:1 #8f8f8f);\n"
"    border: 1px solid #5c5c5c;\n"
"    height: 14px;\n"
"    margin: 0 -5px;\n"
"    border-radius: 7px;\n"
"}\n"
"QSlider::add-page:horizontal {\n"
"    background: white;\n"
"}\n"
"QSlider::add-page:vertical {\n"
"    background: white;\n"
"}\n"
"QSlider::sub-page:horizontal {\n"
"    background: #04b97f;\n"
"}\n"
"QSlider::sub-page:vertical {\n"
"    background: #04b97f;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.rms_main = QtWidgets.QWidget()
        self.rms_main.setObjectName("rms_main")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.rms_main)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame = QtWidgets.QFrame(self.rms_main)
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setStyleSheet("background-color:rgb(19, 19, 19);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_3.addWidget(self.frame_4)
        self.horizontalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_3.setContentsMargins(30, 0, 30, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.label_3 = QtWidgets.QLabel(self.frame_5)
        self.label_3.setMaximumSize(QtCore.QSize(500, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3, 0, QtCore.Qt.AlignHCenter)
        self.label_4 = QtWidgets.QLabel(self.frame_5)
        self.label_4.setMaximumSize(QtCore.QSize(150, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4, 0, QtCore.Qt.AlignHCenter)
        self.label_5 = QtWidgets.QLabel(self.frame_5)
        self.label_5.setMaximumSize(QtCore.QSize(500, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5, 0, QtCore.Qt.AlignHCenter)
        self.rms_main_signup = QtWidgets.QPushButton(self.frame_5)
        self.rms_main_signup.setMaximumSize(QtCore.QSize(200, 200))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.rms_main_signup.setFont(font)
        self.rms_main_signup.setStyleSheet("QPushButton{\n"
"height:40px;\n"
"margin-top:60;\n"
"}")
        self.rms_main_signup.setObjectName("rms_main_signup")
        self.verticalLayout_3.addWidget(self.rms_main_signup, 0, QtCore.Qt.AlignHCenter)
        self.rms_main_login = QtWidgets.QPushButton(self.frame_5)
        self.rms_main_login.setMaximumSize(QtCore.QSize(200, 200))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.rms_main_login.setFont(font)
        self.rms_main_login.setStyleSheet("QPushButton{\n"
"height:40px;\n"
"margin-top:20px;\n"
"}")
        self.rms_main_login.setObjectName("rms_main_login")
        self.verticalLayout_3.addWidget(self.rms_main_login, 0, QtCore.Qt.AlignHCenter)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.horizontalLayout_4.addWidget(self.frame_5)
        self.horizontalLayout.addWidget(self.frame_3)
        self.verticalLayout_4.addWidget(self.frame)
        self.stackedWidget.addWidget(self.rms_main)
        self.rms_signup = QtWidgets.QWidget()
        self.rms_signup.setObjectName("rms_signup")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.rms_signup)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_6 = QtWidgets.QFrame(self.rms_signup)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.back_btn_signup = QtWidgets.QPushButton(self.frame_6)
        self.back_btn_signup.setMinimumSize(QtCore.QSize(100, 50))
        self.back_btn_signup.setStyleSheet("font:16pt;")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../../../mnt/c/Users/prasa/Downloads/left-arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.back_btn_signup.setIcon(icon)
        self.back_btn_signup.setIconSize(QtCore.QSize(20, 20))
        self.back_btn_signup.setObjectName("back_btn_signup")
        self.verticalLayout_5.addWidget(self.back_btn_signup, 0, QtCore.Qt.AlignRight)
        self.frame_7 = QtWidgets.QFrame(self.frame_6)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.frame_7)
        self.label_6.setMinimumSize(QtCore.QSize(0, 0))
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 200))
        self.label_6.setStyleSheet("font: 16pt \"Sans Serif\";")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_6.addWidget(self.label_6)
        self.frame_8 = QtWidgets.QFrame(self.frame_7)
        self.frame_8.setMinimumSize(QtCore.QSize(400, 500))
        self.frame_8.setMaximumSize(QtCore.QSize(3000, 16777215))
        self.frame_8.setStyleSheet("QFrame{\n"
"margin-top:90;\n"
"font:16pt\n"
"}\n"
"QPushButton{\n"
"width:100px;\n"
"}\n"
"")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.rms_signup_username = QtWidgets.QLineEdit(self.frame_8)
        self.rms_signup_username.setMinimumSize(QtCore.QSize(50, 60))
        self.rms_signup_username.setStyleSheet("width:300px;\n"
"font: 16pt \"Sans Serif\";")
        self.rms_signup_username.setText("")
        self.rms_signup_username.setObjectName("rms_signup_username")
        self.verticalLayout_7.addWidget(self.rms_signup_username)
        self.rms_signup_password = QtWidgets.QLineEdit(self.frame_8)
        self.rms_signup_password.setMinimumSize(QtCore.QSize(0, 60))
        self.rms_signup_password.setStyleSheet("font: 16pt \"Sans Serif\";")
        self.rms_signup_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.rms_signup_password.setObjectName("rms_signup_password")
        self.verticalLayout_7.addWidget(self.rms_signup_password)
        self.rms_signup_signupbtn = QtWidgets.QPushButton(self.frame_8)
        self.rms_signup_signupbtn.setMinimumSize(QtCore.QSize(100, 60))
        self.rms_signup_signupbtn.setStyleSheet("font: 16pt \"Sans Serif\";")
        self.rms_signup_signupbtn.setObjectName("rms_signup_signupbtn")
        self.verticalLayout_7.addWidget(self.rms_signup_signupbtn)
        self.verticalLayout_6.addWidget(self.frame_8, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout_5.addWidget(self.frame_7, 0, QtCore.Qt.AlignVCenter)
        self.horizontalLayout_2.addWidget(self.frame_6)
        self.stackedWidget.addWidget(self.rms_signup)
        self.rms_login = QtWidgets.QWidget()
        self.rms_login.setObjectName("rms_login")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.rms_login)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_9 = QtWidgets.QFrame(self.rms_login)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.frame_10 = QtWidgets.QFrame(self.frame_9)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.rms_login_backbtn = QtWidgets.QPushButton(self.frame_10)
        self.rms_login_backbtn.setMinimumSize(QtCore.QSize(100, 50))
        self.rms_login_backbtn.setStyleSheet("font:16pt;")
        self.rms_login_backbtn.setIcon(icon)
        self.rms_login_backbtn.setIconSize(QtCore.QSize(20, 20))
        self.rms_login_backbtn.setObjectName("rms_login_backbtn")
        self.verticalLayout_9.addWidget(self.rms_login_backbtn, 0, QtCore.Qt.AlignRight)
        self.frame_11 = QtWidgets.QFrame(self.frame_10)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_7 = QtWidgets.QLabel(self.frame_11)
        self.label_7.setMinimumSize(QtCore.QSize(0, 0))
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 200))
        self.label_7.setStyleSheet("font: 16pt \"Sans Serif\";")
        self.label_7.setObjectName("label_7")
        self.verticalLayout_10.addWidget(self.label_7)
        self.frame_41 = QtWidgets.QFrame(self.frame_11)
        self.frame_41.setMinimumSize(QtCore.QSize(400, 500))
        self.frame_41.setMaximumSize(QtCore.QSize(3000, 16777215))
        self.frame_41.setStyleSheet("QFrame{\n"
"margin-top:90;\n"
"font:16pt\n"
"}\n"
"QPushButton{\n"
"width:100px;\n"
"}\n"
"")
        self.frame_41.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_41.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_41.setObjectName("frame_41")
        self.verticalLayout_33 = QtWidgets.QVBoxLayout(self.frame_41)
        self.verticalLayout_33.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_33.setSpacing(0)
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.rms_login_username = QtWidgets.QLineEdit(self.frame_41)
        self.rms_login_username.setMinimumSize(QtCore.QSize(50, 60))
        self.rms_login_username.setStyleSheet("width:300px;\n"
"font: 16pt \"Sans Serif\";")
        self.rms_login_username.setText("")
        self.rms_login_username.setObjectName("rms_login_username")
        self.verticalLayout_33.addWidget(self.rms_login_username)
        self.rms_login_password = QtWidgets.QLineEdit(self.frame_41)
        self.rms_login_password.setMinimumSize(QtCore.QSize(0, 60))
        self.rms_login_password.setStyleSheet("font: 16pt \"Sans Serif\";")
        self.rms_login_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.rms_login_password.setObjectName("rms_login_password")
        self.verticalLayout_33.addWidget(self.rms_login_password)
        self.rms_login_loginbtn = QtWidgets.QPushButton(self.frame_41)
        self.rms_login_loginbtn.setMinimumSize(QtCore.QSize(100, 60))
        self.rms_login_loginbtn.setStyleSheet("font: 16pt \"Sans Serif\";")
        self.rms_login_loginbtn.setObjectName("rms_login_loginbtn")
        self.verticalLayout_33.addWidget(self.rms_login_loginbtn)
        self.verticalLayout_10.addWidget(self.frame_41, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout_9.addWidget(self.frame_11, 0, QtCore.Qt.AlignVCenter)
        self.horizontalLayout_17.addWidget(self.frame_10)
        self.horizontalLayout_5.addWidget(self.frame_9)
        self.stackedWidget.addWidget(self.rms_login)
        self.rms_dashboard = QtWidgets.QWidget()
        self.rms_dashboard.setObjectName("rms_dashboard")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.rms_dashboard)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.frame_12 = QtWidgets.QFrame(self.rms_dashboard)
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_12)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_13 = QtWidgets.QFrame(self.frame_12)
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_13)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame_14 = QtWidgets.QFrame(self.frame_13)
        self.frame_14.setMinimumSize(QtCore.QSize(1000, 60))
        self.frame_14.setStyleSheet("QFrame{\n"
"text-align:center;\n"
"}\n"
"")
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_14)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_8 = QtWidgets.QLabel(self.frame_14)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_12.addWidget(self.label_8)
        self.verticalLayout_11.addWidget(self.frame_14)
        self.verticalLayout_8.addWidget(self.frame_13, 0, QtCore.Qt.AlignTop)
        self.frame_15 = QtWidgets.QFrame(self.frame_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_15.sizePolicy().hasHeightForWidth())
        self.frame_15.setSizePolicy(sizePolicy)
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_15)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.frame_16 = QtWidgets.QFrame(self.frame_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_16.sizePolicy().hasHeightForWidth())
        self.frame_16.setSizePolicy(sizePolicy)
        self.frame_16.setMinimumSize(QtCore.QSize(250, 0))
        self.frame_16.setSizeIncrement(QtCore.QSize(0, 0))
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_16)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.frame_17 = QtWidgets.QFrame(self.frame_16)
        self.frame_17.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_17.setStyleSheet("QPushButton{\n"
"padding:20px 10px;\n"
"}\n"
"QPushButton{\n"
"font:16pt;\n"
"}")
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_17)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.profile_btn = QtWidgets.QPushButton(self.frame_17)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../../../../../../mnt/c/Users/prasa/Downloads/user (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.profile_btn.setIcon(icon1)
        self.profile_btn.setIconSize(QtCore.QSize(20, 20))
        self.profile_btn.setObjectName("profile_btn")
        self.verticalLayout_14.addWidget(self.profile_btn)
        self.sales_btn = QtWidgets.QPushButton(self.frame_17)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../../../../../../mnt/c/Users/prasa/Downloads/sales.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sales_btn.setIcon(icon2)
        self.sales_btn.setIconSize(QtCore.QSize(20, 20))
        self.sales_btn.setObjectName("sales_btn")
        self.verticalLayout_14.addWidget(self.sales_btn)
        self.emp_btn = QtWidgets.QPushButton(self.frame_17)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../../../../../../../mnt/c/Users/prasa/Downloads/employee.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.emp_btn.setIcon(icon3)
        self.emp_btn.setIconSize(QtCore.QSize(20, 20))
        self.emp_btn.setObjectName("emp_btn")
        self.verticalLayout_14.addWidget(self.emp_btn)
        self.inventory_btn = QtWidgets.QPushButton(self.frame_17)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../../../../../../../mnt/c/Users/prasa/Downloads/inspection.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.inventory_btn.setIcon(icon4)
        self.inventory_btn.setIconSize(QtCore.QSize(20, 20))
        self.inventory_btn.setObjectName("inventory_btn")
        self.verticalLayout_14.addWidget(self.inventory_btn, 0, QtCore.Qt.AlignTop)
        self.frame_18 = QtWidgets.QFrame(self.frame_17)
        self.frame_18.setStyleSheet("QPushButton{\n"
"padding:20px 10px;\n"
"}\n"
"QPushButton{\n"
"font:16pt;\n"
"}")
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_18)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.logout_btn = QtWidgets.QPushButton(self.frame_18)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../../../../../../../mnt/c/Users/prasa/Downloads/logout.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.logout_btn.setIcon(icon5)
        self.logout_btn.setIconSize(QtCore.QSize(20, 20))
        self.logout_btn.setObjectName("logout_btn")
        self.verticalLayout_15.addWidget(self.logout_btn, 0, QtCore.Qt.AlignBottom)
        self.abt_btn = QtWidgets.QPushButton(self.frame_18)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../../../../../../../mnt/c/Users/prasa/Downloads/information.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.abt_btn.setIcon(icon6)
        self.abt_btn.setIconSize(QtCore.QSize(20, 20))
        self.abt_btn.setObjectName("abt_btn")
        self.verticalLayout_15.addWidget(self.abt_btn)
        self.verticalLayout_14.addWidget(self.frame_18)
        self.verticalLayout_13.addWidget(self.frame_17)
        self.horizontalLayout_7.addWidget(self.frame_16)
        self.frame_19 = QtWidgets.QFrame(self.frame_15)
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frame_19)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setSpacing(0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.frame_19)
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.ProfilePage = QtWidgets.QWidget()
        self.ProfilePage.setObjectName("ProfilePage")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.ProfilePage)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem4)
        self.frame_20 = QtWidgets.QFrame(self.ProfilePage)
        self.frame_20.setMinimumSize(QtCore.QSize(400, 0))
        self.frame_20.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_20.setStyleSheet("QLabel{\n"
"font:16pt;\n"
"}")
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.frame_20)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setSpacing(0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.frame_21 = QtWidgets.QFrame(self.frame_20)
        self.frame_21.setMinimumSize(QtCore.QSize(0, 600))
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_21)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.frame_22 = QtWidgets.QFrame(self.frame_21)
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.frame_22)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_9 = QtWidgets.QLabel(self.frame_22)
        self.label_9.setMinimumSize(QtCore.QSize(0, 75))
        self.label_9.setObjectName("label_9")
        self.verticalLayout_18.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(self.frame_22)
        self.label_10.setMinimumSize(QtCore.QSize(0, 75))
        self.label_10.setObjectName("label_10")
        self.verticalLayout_18.addWidget(self.label_10)
        self.label_11 = QtWidgets.QLabel(self.frame_22)
        self.label_11.setMinimumSize(QtCore.QSize(0, 75))
        self.label_11.setObjectName("label_11")
        self.verticalLayout_18.addWidget(self.label_11)
        self.label_12 = QtWidgets.QLabel(self.frame_22)
        self.label_12.setMinimumSize(QtCore.QSize(0, 75))
        self.label_12.setObjectName("label_12")
        self.verticalLayout_18.addWidget(self.label_12)
        self.label_13 = QtWidgets.QLabel(self.frame_22)
        self.label_13.setMinimumSize(QtCore.QSize(0, 75))
        self.label_13.setStyleSheet("")
        self.label_13.setObjectName("label_13")
        self.verticalLayout_18.addWidget(self.label_13)
        self.horizontalLayout_9.addWidget(self.frame_22)
        self.frame_23 = QtWidgets.QFrame(self.frame_21)
        self.frame_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.frame_23)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.rms_profile_username = QtWidgets.QLabel(self.frame_23)
        self.rms_profile_username.setMinimumSize(QtCore.QSize(0, 75))
        self.rms_profile_username.setObjectName("rms_profile_username")
        self.verticalLayout_19.addWidget(self.rms_profile_username)
        self.rms_profile_age = QtWidgets.QLabel(self.frame_23)
        self.rms_profile_age.setMinimumSize(QtCore.QSize(0, 75))
        self.rms_profile_age.setObjectName("rms_profile_age")
        self.verticalLayout_19.addWidget(self.rms_profile_age)
        self.rms_profile_gender = QtWidgets.QLabel(self.frame_23)
        self.rms_profile_gender.setMinimumSize(QtCore.QSize(0, 75))
        self.rms_profile_gender.setObjectName("rms_profile_gender")
        self.verticalLayout_19.addWidget(self.rms_profile_gender)
        self.rms_profile_email = QtWidgets.QLabel(self.frame_23)
        self.rms_profile_email.setMinimumSize(QtCore.QSize(0, 75))
        self.rms_profile_email.setObjectName("rms_profile_email")
        self.verticalLayout_19.addWidget(self.rms_profile_email)
        self.rms_profile_role = QtWidgets.QLabel(self.frame_23)
        self.rms_profile_role.setMinimumSize(QtCore.QSize(0, 75))
        self.rms_profile_role.setStyleSheet("")
        self.rms_profile_role.setObjectName("rms_profile_role")
        self.verticalLayout_19.addWidget(self.rms_profile_role)
        self.horizontalLayout_9.addWidget(self.frame_23)
        self.verticalLayout_17.addWidget(self.frame_21, 0, QtCore.Qt.AlignVCenter)
        self.horizontalLayout_8.addWidget(self.frame_20)
        self.frame_24 = QtWidgets.QFrame(self.ProfilePage)
        self.frame_24.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_24.setObjectName("frame_24")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.frame_24)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.label_19 = QtWidgets.QLabel(self.frame_24)
        self.label_19.setStyleSheet("QLabel{\n"
"border-radius:100;\n"
"}")
        self.label_19.setText("")
        self.label_19.setPixmap(QtGui.QPixmap("../../../../../../../mnt/c/Users/prasa/Downloads/user_profile (1).jpg"))
        self.label_19.setObjectName("label_19")
        self.verticalLayout_20.addWidget(self.label_19)
        self.horizontalLayout_8.addWidget(self.frame_24, 0, QtCore.Qt.AlignHCenter)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem5)
        self.stackedWidget_2.addWidget(self.ProfilePage)
        self.Employee = QtWidgets.QWidget()
        self.Employee.setObjectName("Employee")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.Employee)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.frame_25 = QtWidgets.QFrame(self.Employee)
        self.frame_25.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_25.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_25.setObjectName("frame_25")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.frame_25)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.frame_26 = QtWidgets.QFrame(self.frame_25)
        self.frame_26.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_26.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_26.setObjectName("frame_26")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.frame_26)
        self.verticalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_23.setSpacing(0)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.frame_27 = QtWidgets.QFrame(self.frame_26)
        self.frame_27.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_27.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_27.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_27.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_27.setObjectName("frame_27")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_27)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.frame_28 = QtWidgets.QFrame(self.frame_27)
        self.frame_28.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_28.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_28.setObjectName("frame_28")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_28)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.rms_employees_searchLineEdit = QtWidgets.QLineEdit(self.frame_28)
        self.rms_employees_searchLineEdit.setMinimumSize(QtCore.QSize(600, 50))
        self.rms_employees_searchLineEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.rms_employees_searchLineEdit.setStyleSheet("font:16pt")
        self.rms_employees_searchLineEdit.setObjectName("rms_employees_searchLineEdit")
        self.horizontalLayout_11.addWidget(self.rms_employees_searchLineEdit)
        spacerItem6 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem6)
        self.rms_employees_searchbtn = QtWidgets.QPushButton(self.frame_28)
        self.rms_employees_searchbtn.setMinimumSize(QtCore.QSize(0, 50))
        self.rms_employees_searchbtn.setStyleSheet("font:16pt;\n"
"margin-right:10;")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("../../../../../../../mnt/c/Users/prasa/Downloads/magnifying-glass.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rms_employees_searchbtn.setIcon(icon7)
        self.rms_employees_searchbtn.setIconSize(QtCore.QSize(20, 20))
        self.rms_employees_searchbtn.setObjectName("rms_employees_searchbtn")
        self.horizontalLayout_11.addWidget(self.rms_employees_searchbtn)
        self.horizontalLayout_10.addWidget(self.frame_28)
        self.verticalLayout_23.addWidget(self.frame_27)
        self.frame_29 = QtWidgets.QFrame(self.frame_26)
        self.frame_29.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_29.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_29.setObjectName("frame_29")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.frame_29)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.frame_30 = QtWidgets.QFrame(self.frame_29)
        self.frame_30.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_30.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_30.setObjectName("frame_30")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.frame_30)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.tableWidget = QtWidgets.QTableWidget(self.frame_30)
        self.tableWidget.setStyleSheet("font:12pt;")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.verticalLayout_25.addWidget(self.tableWidget)
        self.verticalLayout_24.addWidget(self.frame_30)
        self.frame_31 = QtWidgets.QFrame(self.frame_29)
        self.frame_31.setMaximumSize(QtCore.QSize(500, 100))
        self.frame_31.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_31.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_31.setObjectName("frame_31")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.frame_31)
        self.verticalLayout_26.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_26.setSpacing(0)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.frame_32 = QtWidgets.QFrame(self.frame_31)
        self.frame_32.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_32.setMaximumSize(QtCore.QSize(500, 100))
        self.frame_32.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_32.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_32.setObjectName("frame_32")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_32)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(9)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.rms_employees_updatebtn = QtWidgets.QPushButton(self.frame_32)
        self.rms_employees_updatebtn.setStyleSheet("font:16pt;\n"
"padding:10px 20px")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("../../../../../../../mnt/c/Users/prasa/Downloads/update.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rms_employees_updatebtn.setIcon(icon8)
        self.rms_employees_updatebtn.setIconSize(QtCore.QSize(20, 20))
        self.rms_employees_updatebtn.setObjectName("rms_employees_updatebtn")
        self.horizontalLayout_12.addWidget(self.rms_employees_updatebtn)
        self.verticalLayout_26.addWidget(self.frame_32)
        self.verticalLayout_24.addWidget(self.frame_31, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_23.addWidget(self.frame_29)
        self.verticalLayout_22.addWidget(self.frame_26)
        self.verticalLayout_21.addWidget(self.frame_25)
        self.stackedWidget_2.addWidget(self.Employee)
        self.rms_update_employee = QtWidgets.QWidget()
        self.rms_update_employee.setObjectName("rms_update_employee")
        self.verticalLayout_35 = QtWidgets.QVBoxLayout(self.rms_update_employee)
        self.verticalLayout_35.setObjectName("verticalLayout_35")
        self.frame_43 = QtWidgets.QFrame(self.rms_update_employee)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_43.sizePolicy().hasHeightForWidth())
        self.frame_43.setSizePolicy(sizePolicy)
        self.frame_43.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_43.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_43.setObjectName("frame_43")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_43)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem7)
        self.frame_45 = QtWidgets.QFrame(self.frame_43)
        self.frame_45.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_45.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_45.setObjectName("frame_45")
        self.verticalLayout_37 = QtWidgets.QVBoxLayout(self.frame_45)
        self.verticalLayout_37.setObjectName("verticalLayout_37")
        self.update_name = QtWidgets.QLabel(self.frame_45)
        self.update_name.setObjectName("update_name")
        self.verticalLayout_37.addWidget(self.update_name)
        self.update_username = QtWidgets.QLabel(self.frame_45)
        self.update_username.setObjectName("update_username")
        self.verticalLayout_37.addWidget(self.update_username)
        self.label_22 = QtWidgets.QLabel(self.frame_45)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_37.addWidget(self.label_22)
        self.label_23 = QtWidgets.QLabel(self.frame_45)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_37.addWidget(self.label_23)
        self.label_24 = QtWidgets.QLabel(self.frame_45)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_37.addWidget(self.label_24)
        self.label_25 = QtWidgets.QLabel(self.frame_45)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_37.addWidget(self.label_25)
        self.horizontalLayout_6.addWidget(self.frame_45)
        self.frame_46 = QtWidgets.QFrame(self.frame_43)
        self.frame_46.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_46.setMaximumSize(QtCore.QSize(1677215, 16777215))
        self.frame_46.setStyleSheet("QLineEdit{\n"
"height:50px;\n"
"font:16pt;\n"
"}")
        self.frame_46.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_46.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_46.setObjectName("frame_46")
        self.verticalLayout_38 = QtWidgets.QVBoxLayout(self.frame_46)
        self.verticalLayout_38.setObjectName("verticalLayout_38")
        self.rms_update_employee_name = QtWidgets.QLineEdit(self.frame_46)
        self.rms_update_employee_name.setStyleSheet("width:300px;\n"
"height:50px")
        self.rms_update_employee_name.setObjectName("rms_update_employee_name")
        self.verticalLayout_38.addWidget(self.rms_update_employee_name)
        self.rms_update_employee_username = QtWidgets.QLineEdit(self.frame_46)
        self.rms_update_employee_username.setObjectName("rms_update_employee_username")
        self.verticalLayout_38.addWidget(self.rms_update_employee_username)
        self.update_email = QtWidgets.QLineEdit(self.frame_46)
        self.update_email.setObjectName("update_email")
        self.verticalLayout_38.addWidget(self.update_email)
        self.update_age = QtWidgets.QLineEdit(self.frame_46)
        self.update_age.setObjectName("update_age")
        self.verticalLayout_38.addWidget(self.update_age)
        self.update_gender = QtWidgets.QLineEdit(self.frame_46)
        self.update_gender.setObjectName("update_gender")
        self.verticalLayout_38.addWidget(self.update_gender)
        self.update_role = QtWidgets.QLineEdit(self.frame_46)
        self.update_role.setObjectName("update_role")
        self.verticalLayout_38.addWidget(self.update_role)
        self.horizontalLayout_6.addWidget(self.frame_46, 0, QtCore.Qt.AlignHCenter)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem8)
        self.verticalLayout_35.addWidget(self.frame_43)
        self.frame_44 = QtWidgets.QFrame(self.rms_update_employee)
        self.frame_44.setMinimumSize(QtCore.QSize(400, 0))
        self.frame_44.setMaximumSize(QtCore.QSize(200, 16777215))
        self.frame_44.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_44.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_44.setObjectName("frame_44")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout(self.frame_44)
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.rms_update_emp_removebtn = QtWidgets.QPushButton(self.frame_44)
        self.rms_update_emp_removebtn.setMinimumSize(QtCore.QSize(120, 75))
        self.rms_update_emp_removebtn.setStyleSheet("font:16pt;")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("../../../../../../../mnt/c/Users/prasa/Downloads/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rms_update_emp_removebtn.setIcon(icon9)
        self.rms_update_emp_removebtn.setIconSize(QtCore.QSize(20, 20))
        self.rms_update_emp_removebtn.setObjectName("rms_update_emp_removebtn")
        self.horizontalLayout_29.addWidget(self.rms_update_emp_removebtn)
        self.rms_update_screen_update_btn = QtWidgets.QPushButton(self.frame_44)
        self.rms_update_screen_update_btn.setMinimumSize(QtCore.QSize(120, 75))
        self.rms_update_screen_update_btn.setStyleSheet("font:16pt;")
        self.rms_update_screen_update_btn.setIcon(icon8)
        self.rms_update_screen_update_btn.setIconSize(QtCore.QSize(20, 20))
        self.rms_update_screen_update_btn.setObjectName("rms_update_screen_update_btn")
        self.horizontalLayout_29.addWidget(self.rms_update_screen_update_btn)
        self.verticalLayout_35.addWidget(self.frame_44, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignBottom)
        self.stackedWidget_2.addWidget(self.rms_update_employee)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_66 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_66.setObjectName("verticalLayout_66")
        self.frame_73 = QtWidgets.QFrame(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_73.sizePolicy().hasHeightForWidth())
        self.frame_73.setSizePolicy(sizePolicy)
        self.frame_73.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_73.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_73.setObjectName("frame_73")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout(self.frame_73)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_28.addItem(spacerItem9)
        self.frame_76 = QtWidgets.QFrame(self.frame_73)
        self.frame_76.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_76.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_76.setObjectName("frame_76")
        self.verticalLayout_64 = QtWidgets.QVBoxLayout(self.frame_76)
        self.verticalLayout_64.setObjectName("verticalLayout_64")
        self.label_54 = QtWidgets.QLabel(self.frame_76)
        self.label_54.setObjectName("label_54")
        self.verticalLayout_64.addWidget(self.label_54)
        self.label_55 = QtWidgets.QLabel(self.frame_76)
        self.label_55.setObjectName("label_55")
        self.verticalLayout_64.addWidget(self.label_55)
        self.label_51 = QtWidgets.QLabel(self.frame_76)
        self.label_51.setObjectName("label_51")
        self.verticalLayout_64.addWidget(self.label_51)
        self.label_52 = QtWidgets.QLabel(self.frame_76)
        self.label_52.setObjectName("label_52")
        self.verticalLayout_64.addWidget(self.label_52)
        self.label_53 = QtWidgets.QLabel(self.frame_76)
        self.label_53.setObjectName("label_53")
        self.verticalLayout_64.addWidget(self.label_53)
        self.horizontalLayout_28.addWidget(self.frame_76)
        self.frame_77 = QtWidgets.QFrame(self.frame_73)
        self.frame_77.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_77.setMaximumSize(QtCore.QSize(1677215, 16777215))
        self.frame_77.setStyleSheet("QLineEdit{\n"
"height:50px;\n"
"font:16pt;\n"
"}")
        self.frame_77.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_77.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_77.setObjectName("frame_77")
        self.verticalLayout_65 = QtWidgets.QVBoxLayout(self.frame_77)
        self.verticalLayout_65.setObjectName("verticalLayout_65")
        self.update_product_name = QtWidgets.QLineEdit(self.frame_77)
        self.update_product_name.setStyleSheet("width:300px;\n"
"height:50px")
        self.update_product_name.setObjectName("update_product_name")
        self.verticalLayout_65.addWidget(self.update_product_name)
        self.update_category = QtWidgets.QLineEdit(self.frame_77)
        self.update_category.setObjectName("update_category")
        self.verticalLayout_65.addWidget(self.update_category)
        self.update_description = QtWidgets.QLineEdit(self.frame_77)
        self.update_description.setObjectName("update_description")
        self.verticalLayout_65.addWidget(self.update_description)
        self.update_stock = QtWidgets.QLineEdit(self.frame_77)
        self.update_stock.setObjectName("update_stock")
        self.verticalLayout_65.addWidget(self.update_stock)
        self.update_price = QtWidgets.QLineEdit(self.frame_77)
        self.update_price.setObjectName("update_price")
        self.verticalLayout_65.addWidget(self.update_price)
        self.horizontalLayout_28.addWidget(self.frame_77, 0, QtCore.Qt.AlignHCenter)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_28.addItem(spacerItem10)
        self.verticalLayout_66.addWidget(self.frame_73)
        self.frame_47 = QtWidgets.QFrame(self.page)
        self.frame_47.setMinimumSize(QtCore.QSize(300, 0))
        self.frame_47.setMaximumSize(QtCore.QSize(200, 16777215))
        self.frame_47.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_47.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_47.setObjectName("frame_47")
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout(self.frame_47)
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.rms_inventory_product_update_btn = QtWidgets.QPushButton(self.frame_47)
        self.rms_inventory_product_update_btn.setMinimumSize(QtCore.QSize(0, 75))
        self.rms_inventory_product_update_btn.setStyleSheet("font:16pt;")
        self.rms_inventory_product_update_btn.setIcon(icon9)
        self.rms_inventory_product_update_btn.setIconSize(QtCore.QSize(20, 20))
        self.rms_inventory_product_update_btn.setObjectName("rms_inventory_product_update_btn")
        self.horizontalLayout_30.addWidget(self.rms_inventory_product_update_btn)
        self.rms_updateprod_screen_update_btn = QtWidgets.QPushButton(self.frame_47)
        self.rms_updateprod_screen_update_btn.setMinimumSize(QtCore.QSize(120, 75))
        self.rms_updateprod_screen_update_btn.setStyleSheet("font:16pt;")
        self.rms_updateprod_screen_update_btn.setIcon(icon8)
        self.rms_updateprod_screen_update_btn.setIconSize(QtCore.QSize(20, 20))
        self.rms_updateprod_screen_update_btn.setObjectName("rms_updateprod_screen_update_btn")
        self.horizontalLayout_30.addWidget(self.rms_updateprod_screen_update_btn)
        self.verticalLayout_66.addWidget(self.frame_47, 0, QtCore.Qt.AlignHCenter)
        self.stackedWidget_2.addWidget(self.page)
        self.Inventory = QtWidgets.QWidget()
        self.Inventory.setObjectName("Inventory")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout(self.Inventory)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.frame_33 = QtWidgets.QFrame(self.Inventory)
        self.frame_33.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_33.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_33.setObjectName("frame_33")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout(self.frame_33)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.frame_34 = QtWidgets.QFrame(self.frame_33)
        self.frame_34.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_34.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_34.setObjectName("frame_34")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout(self.frame_34)
        self.verticalLayout_29.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_29.setSpacing(0)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.frame_35 = QtWidgets.QFrame(self.frame_34)
        self.frame_35.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_35.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_35.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_35.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_35.setObjectName("frame_35")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_35)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.frame_36 = QtWidgets.QFrame(self.frame_35)
        self.frame_36.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_36.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_36.setObjectName("frame_36")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_36)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.rms_inventory_lineEdit = QtWidgets.QLineEdit(self.frame_36)
        self.rms_inventory_lineEdit.setMinimumSize(QtCore.QSize(600, 50))
        self.rms_inventory_lineEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.rms_inventory_lineEdit.setStyleSheet("font:16pt")
        self.rms_inventory_lineEdit.setObjectName("rms_inventory_lineEdit")
        self.horizontalLayout_14.addWidget(self.rms_inventory_lineEdit)
        spacerItem11 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem11)
        self.rms_inventory_searchbtn = QtWidgets.QPushButton(self.frame_36)
        self.rms_inventory_searchbtn.setMinimumSize(QtCore.QSize(0, 50))
        self.rms_inventory_searchbtn.setStyleSheet("font:16pt;\n"
"margin-right:10;")
        self.rms_inventory_searchbtn.setIcon(icon7)
        self.rms_inventory_searchbtn.setIconSize(QtCore.QSize(20, 20))
        self.rms_inventory_searchbtn.setObjectName("rms_inventory_searchbtn")
        self.horizontalLayout_14.addWidget(self.rms_inventory_searchbtn)
        self.horizontalLayout_13.addWidget(self.frame_36)
        self.verticalLayout_29.addWidget(self.frame_35)
        self.frame_37 = QtWidgets.QFrame(self.frame_34)
        self.frame_37.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_37.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_37.setObjectName("frame_37")
        self.verticalLayout_30 = QtWidgets.QVBoxLayout(self.frame_37)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.frame_38 = QtWidgets.QFrame(self.frame_37)
        self.frame_38.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_38.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_38.setObjectName("frame_38")
        self.verticalLayout_31 = QtWidgets.QVBoxLayout(self.frame_38)
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.frame_38)
        self.tableWidget_2.setStyleSheet("font:12pt;")
        self.tableWidget_2.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(6)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        self.verticalLayout_31.addWidget(self.tableWidget_2)
        self.verticalLayout_30.addWidget(self.frame_38)
        self.frame_39 = QtWidgets.QFrame(self.frame_37)
        self.frame_39.setMaximumSize(QtCore.QSize(500, 100))
        self.frame_39.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_39.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_39.setObjectName("frame_39")
        self.verticalLayout_32 = QtWidgets.QVBoxLayout(self.frame_39)
        self.verticalLayout_32.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_32.setSpacing(0)
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.frame_40 = QtWidgets.QFrame(self.frame_39)
        self.frame_40.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_40.setMaximumSize(QtCore.QSize(500, 100))
        self.frame_40.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_40.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_40.setObjectName("frame_40")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_40)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setSpacing(9)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.rms_inventory_updatebtn = QtWidgets.QPushButton(self.frame_40)
        self.rms_inventory_updatebtn.setStyleSheet("font:16pt;\n"
"padding:10px 20px")
        self.rms_inventory_updatebtn.setIcon(icon8)
        self.rms_inventory_updatebtn.setIconSize(QtCore.QSize(20, 20))
        self.rms_inventory_updatebtn.setObjectName("rms_inventory_updatebtn")
        self.horizontalLayout_15.addWidget(self.rms_inventory_updatebtn)
        self.verticalLayout_32.addWidget(self.frame_40)
        self.verticalLayout_30.addWidget(self.frame_39, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_29.addWidget(self.frame_37)
        self.verticalLayout_28.addWidget(self.frame_34)
        self.verticalLayout_27.addWidget(self.frame_33)
        self.stackedWidget_2.addWidget(self.Inventory)
        self.verticalLayout_16.addWidget(self.stackedWidget_2)
        self.horizontalLayout_7.addWidget(self.frame_19)
        self.verticalLayout_8.addWidget(self.frame_15)
        self.horizontalLayout_16.addWidget(self.frame_12)
        self.stackedWidget.addWidget(self.rms_dashboard)
        self.verticalLayout.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.stackedWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Retail Management</span></p></body></html>"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">System</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Create new account</p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">or</p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Login to your existing account</p></body></html>"))
        self.rms_main_signup.setText(_translate("MainWindow", "Sign Up"))
        self.rms_main_login.setText(_translate("MainWindow", "Login"))
        self.back_btn_signup.setText(_translate("MainWindow", "Back"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:26pt; font-weight:600;\">Create a new account</span></p></body></html>"))
        self.rms_signup_username.setPlaceholderText(_translate("MainWindow", "Username"))
        self.rms_signup_password.setPlaceholderText(_translate("MainWindow", "Password"))
        self.rms_signup_signupbtn.setText(_translate("MainWindow", "SignUp"))
        self.rms_login_backbtn.setText(_translate("MainWindow", "Back"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; font-weight:600;\">Login to your existing account<br/></span></p></body></html>"))
        self.rms_login_username.setPlaceholderText(_translate("MainWindow", "Username"))
        self.rms_login_password.setPlaceholderText(_translate("MainWindow", "Password"))
        self.rms_login_loginbtn.setText(_translate("MainWindow", "Login"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; font-weight:600;\">Retail Management System</span></p></body></html>"))
        self.profile_btn.setText(_translate("MainWindow", "Profile"))
        self.sales_btn.setText(_translate("MainWindow", "Sales"))
        self.emp_btn.setText(_translate("MainWindow", "Employees"))
        self.inventory_btn.setText(_translate("MainWindow", "Inventory"))
        self.logout_btn.setText(_translate("MainWindow", "Logout"))
        self.abt_btn.setText(_translate("MainWindow", "About"))
        self.label_9.setText(_translate("MainWindow", " Username :"))
        self.label_10.setText(_translate("MainWindow", "Age :"))
        self.label_11.setText(_translate("MainWindow", "Gender :"))
        self.label_12.setText(_translate("MainWindow", "Email :"))
        self.label_13.setText(_translate("MainWindow", "Role :"))
        self.rms_profile_username.setText(_translate("MainWindow", " Username :"))
        self.rms_profile_age.setText(_translate("MainWindow", "Age :"))
        self.rms_profile_gender.setText(_translate("MainWindow", "Gender :"))
        self.rms_profile_email.setText(_translate("MainWindow", "Email :"))
        self.rms_profile_role.setText(_translate("MainWindow", "Role :"))
        self.rms_employees_searchLineEdit.setPlaceholderText(_translate("MainWindow", "Search for an employee"))
        self.rms_employees_searchbtn.setText(_translate("MainWindow", "Search"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Name"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Username"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Email"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Age"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Gender"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Role"))
        self.rms_employees_updatebtn.setText(_translate("MainWindow", "Update"))
        self.update_name.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">Name</span></p></body></html>"))
        self.update_username.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">Username</span></p></body></html>"))
        self.label_22.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">Email</span></p></body></html>"))
        self.label_23.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">Age</span></p></body></html>"))
        self.label_24.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">Gender</span></p></body></html>"))
        self.label_25.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">Role</span></p></body></html>"))
        self.rms_update_emp_removebtn.setText(_translate("MainWindow", "Remove Employee"))
        self.rms_update_screen_update_btn.setText(_translate("MainWindow", "Update"))
        self.label_54.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">Product Name</span></p></body></html>"))
        self.label_55.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">Category</span></p></body></html>"))
        self.label_51.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">Description</span></p></body></html>"))
        self.label_52.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">Stock</span></p></body></html>"))
        self.label_53.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">Price</span></p></body></html>"))
        self.rms_inventory_product_update_btn.setText(_translate("MainWindow", "Remove"))
        self.rms_updateprod_screen_update_btn.setText(_translate("MainWindow", "Update"))
        self.rms_inventory_lineEdit.setPlaceholderText(_translate("MainWindow", "Search for a product"))
        self.rms_inventory_searchbtn.setText(_translate("MainWindow", "Search"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ProductId"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Category"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Description"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Stock"))
        item = self.tableWidget_2.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Price"))
        self.rms_inventory_updatebtn.setText(_translate("MainWindow", "Update"))
        
        #***************************************************************************************************************
        self.tableWidget.setColumnWidth(0,268)
        self.tableWidget.setColumnWidth(1,248)
        self.tableWidget.setColumnWidth(2,335)
        self.tableWidget.setColumnWidth(3,111)
        self.tableWidget.setColumnWidth(4,263)
        self.tableWidget.setColumnWidth(5,321)
        self.tableWidget_2.setColumnWidth(0,196)
        self.tableWidget_2.setColumnWidth(1,247)
        self.tableWidget_2.setColumnWidth(2,275)
        self.tableWidget_2.setColumnWidth(3,414)
        self.tableWidget_2.setColumnWidth(4,226)
        self.tableWidget_2.setColumnWidth(5,197)
        self.rms_main_login.clicked.connect(lambda:self.stackedWidget.setCurrentWidget(self.rms_login))
        self.rms_main_signup.clicked.connect(lambda:self.stackedWidget.setCurrentWidget(self.rms_signup))
        self.rms_login_backbtn.clicked.connect(lambda: self.stackedWidget.setCurrentWidget(self.rms_main))
        self.back_btn_signup.clicked.connect(lambda: self.stackedWidget.setCurrentWidget(self.rms_main))
        self.emp_btn.clicked.connect(lambda: self.stackedWidget_2.setCurrentWidget(self.Employee))
        self.emp_btn.clicked.connect(self.populate_employee)
        self.inventory_btn.clicked.connect(self.populate_stocks)
        self.profile_btn.clicked.connect(lambda: self.stackedWidget_2.setCurrentWidget(self.ProfilePage))
        self.inventory_btn.clicked.connect(lambda: self.stackedWidget_2.setCurrentWidget(self.Inventory))
        self.rms_login_loginbtn.clicked.connect(self.on_login)
        self.rms_employees_updatebtn.clicked.connect(self.showUpdateEmpScreen)
        self.rms_inventory_updatebtn.clicked.connect(self.show_page)
        self.tableWidget_2.clicked.connect(self.handle_product_click)
        self.tableWidget.clicked.connect(self.handle_emp_click)
        self.rms_updateprod_screen_update_btn.clicked.connect(self.update_product_details)
        self.rms_update_screen_update_btn.clicked.connect(self.update_emp_details)
    def showUpdateEmpScreen(self):
            self.stackedWidget_2.setCurrentWidget(self.rms_update_employee)
            emp_name = ""
            emp_role = ""
            emp_username = ""
            emp_email = ""
            emp_age = ""
            emp_gender = ""
            print(self.selected_emp)
            for item in self.selected_emp:
                if "Name" in item:
                        emp_name = item["Name"]
                elif "Username" in item:
                        emp_username = item["Username"]
                elif "Email" in item:
                        emp_email = item["Email"]
                elif "Age" in item:
                        emp_age = item["Age"]
                elif "Role" in item:
                        emp_role = item["Role"]
                elif "Gender" in item:
                        emp_gender = item["Gender"]
            self.rms_update_employee_name.setText(emp_name)
            self.update_age.setText(emp_age)
            self.update_email.setText(emp_email)
            self.update_role.setText(emp_role)
            self.rms_update_employee_username.setText(emp_username)
            self.update_gender.setText(emp_gender)
    def update_emp_details(self):
            emp_name=self.rms_update_employee_name.text()
            emp_username = self.rms_update_employee_username.text()
            emp_email=self.update_email.text()
            emp_role= self.update_role.text()
            emp_age = self.update_age.text()
            emp_gender = self.update_gender.text()
            update_emp_handler(emp_name,emp_username,emp_email,emp_role,emp_age,emp_gender)
            
    def update_product_details(self):
            produt_name=self.update_product_name.text()
            product_description = self.update_description.text()
            product_stock=self.update_stock.text()
            product_price= self.update_price.text()
            product_category = self.update_category.text()
            update_product_handler(produt_name,product_description,product_stock,product_price,product_category)
            
        
    def show_page(self):
            self.stackedWidget_2.setCurrentWidget(self.page)
            product_name = ""
            product_category = ""
            product_description = ""
            product_stock = ""
    
            for item in self.selected_product:
                if "Name" in item:
                        product_name = item["Name"]
                elif "Category" in item:
                        product_category = item["Category"]
                elif "Description" in item:
                        product_description = item["Description"]
                elif "Stock" in item:
                        product_stock = item["Stock"]
                elif "ProductId" in item:
                        product_productId = item["ProductId"]
                elif "Price" in item:
                        product_Price = item["Price"]
    
            self.update_product_name.setText(product_name)
            self.update_category.setText(product_category)
            self.update_description.setText(product_description)
            self.update_price.setText(product_Price)
            self.update_stock.setText(product_stock)
    def handle_product_click(self,index):
             row = index.row()
             self.selected_product = self.get_row_items(row)
    def handle_emp_click(self,index):
             row = index.row()
             self.selected_emp = self.get_row_emp_items(row)
    def get_row_items(self, row):
        column_count = self.tableWidget_2.columnCount()
        row_items = []
        for column in range(column_count):
                item = self.tableWidget_2.item(row, column)
                column_name = self.tableWidget_2.horizontalHeaderItem(column).text()
                if item is not None:
                    row_items.append({column_name: item.text()})
                else:
                    row_items.append({column_name: None})
        
        return row_items

    def get_row_emp_items(self, row):
        column_count = self.tableWidget.columnCount()
        row_items = []
        for column in range(column_count):
                item = self.tableWidget.item(row, column)
                column_name = self.tableWidget.horizontalHeaderItem(column).text()
                if item is not None:
                    row_items.append({column_name: item.text()})
                else:
                    row_items.append({column_name: None})
        
        return row_items
                
    def populate_stocks(self):
            stock_details = get_all_product_details();
            self.tableWidget_2.setRowCount(len(stock_details))
            row = 0
            for stock in stock_details:
                    self.tableWidget_2.setItem(row,0,QtWidgets.QTableWidgetItem(str(stock['id']).title()))
                    self.tableWidget_2.setItem(row,1,QtWidgets.QTableWidgetItem(str(stock['name']).title()))
                    self.tableWidget_2.setItem(row,2,QtWidgets.QTableWidgetItem(str(stock['category']).title()))
                    self.tableWidget_2.setItem(row,3,QtWidgets.QTableWidgetItem(str(stock['description']).title()))
                    self.tableWidget_2.setItem(row,4,QtWidgets.QTableWidgetItem(str(stock['stock']).title()))
                    self.tableWidget_2.setItem(row,5,QtWidgets.QTableWidgetItem(str(stock['price']).title()))
                    row+=1

                        
    def populate_employee(self):
        employee_details =  get_all_employee_details()
        self.tableWidget.setRowCount(len(employee_details))
        row=0
        for employee in employee_details:
                self.tableWidget.setItem(row,0,QtWidgets.QTableWidgetItem(str(employee['name']).title()))
                self.tableWidget.setItem(row,1,QtWidgets.QTableWidgetItem(str(employee['username'])))
                self.tableWidget.setItem(row,2,QtWidgets.QTableWidgetItem(employee['email']))
                self.tableWidget.setItem(row,3,QtWidgets.QTableWidgetItem(str(employee['age'])))
                self.tableWidget.setItem(row,4,QtWidgets.QTableWidgetItem(str(employee['gender']).title()))
                self.tableWidget.setItem(row,5,QtWidgets.QTableWidgetItem(str(employee['role']).title()))
                row+=1
     
    def on_login(self):
        username = self.rms_login_username.text()
        password = self.rms_login_password.text()
        result = login(username,password)
        if(result):
                self.username = username
                self.rms_login_loginbtn.setText("Click here for dashboard access.")
                self.rms_login_loginbtn.clicked.connect(lambda: self.stackedWidget.setCurrentWidget(self.rms_dashboard))
                employee_details = get_employee_details(username)
                id, age, email, role, gender = employee_details
                self.id = id
                self.age = age
                self.email=email
                self.role=role
                self.gender=gender
                self.rms_profile_username.setText(str(self.username).title())
                self.rms_profile_age.setText(str(self.age))
                self.rms_profile_gender.setText(str(self.gender).title())
                self.rms_profile_email.setText(str(self.email))
                self.rms_profile_role.setText(str(self.role).title())
        


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
